using UPACIP.DataAccess.Entities;
using UPACIP.DataAccess.Enums;

namespace UPACIP.Service.Coding;

// ─────────────────────────────────────────────────────────────────────────────
// Result / DTO types
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// A single item in the staff verification queue — one AI-suggested <see cref="MedicalCode"/>
/// enriched with the fields staff need to make an approve/override decision (US_049 AC-1).
/// </summary>
public sealed record VerificationQueueItem
{
    /// <summary>Primary key of the <see cref="MedicalCode"/> row.</summary>
    public Guid CodeId { get; init; }

    /// <summary>Coding standard (<c>Icd10</c> or <c>Cpt</c>).</summary>
    public CodeType CodeType { get; init; }

    /// <summary>The AI-suggested code value (e.g. "J18.9" or "99213").</summary>
    public string CodeValue { get; init; } = string.Empty;

    /// <summary>Human-readable description of the code.</summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>Clinical justification generated by the AI pipeline.</summary>
    public string Justification { get; init; } = string.Empty;

    /// <summary>AI confidence score in the range [0.0, 1.0]; <c>null</c> for manually entered codes.</summary>
    public float? AiConfidenceScore { get; init; }

    /// <summary>Current review state of this code record.</summary>
    public CodeVerificationStatus VerificationStatus { get; init; }

    /// <summary>
    /// <c>true</c> when the code library marks this code value as deprecated.
    /// Staff must not approve deprecated codes; the UI should show a deprecation notice (EC-1).
    /// </summary>
    public bool IsDeprecated { get; init; }

    /// <summary>UTC timestamp when the AI-generated code was first persisted.</summary>
    public DateTime CreatedAt { get; init; }
}

/// <summary>
/// Verification progress summary for a patient — used to derive the "partially verified"
/// progress indicator on the medical coding screen (US_049 EC-2).
/// </summary>
public sealed record VerificationProgress
{
    /// <summary>Total number of <see cref="MedicalCode"/> rows for the patient.</summary>
    public int Total { get; init; }

    /// <summary>Number of codes with <see cref="CodeVerificationStatus.Verified"/>.</summary>
    public int Verified { get; init; }

    /// <summary>Number of codes with <see cref="CodeVerificationStatus.Overridden"/>.</summary>
    public int Overridden { get; init; }

    /// <summary>Number of codes with <see cref="CodeVerificationStatus.Pending"/>.</summary>
    public int Pending { get; init; }

    /// <summary>Number of codes with <see cref="CodeVerificationStatus.Deprecated"/>.</summary>
    public int Deprecated { get; init; }

    /// <summary>
    /// Derived human-readable label:
    /// <list type="bullet">
    ///   <item><c>"fully verified"</c>     — zero pending/deprecated codes remain.</item>
    ///   <item><c>"partially verified"</c> — at least one code reviewed, at least one still pending.</item>
    ///   <item><c>"pending review"</c>     — no codes have been reviewed yet.</item>
    /// </list>
    /// </summary>
    public string StatusLabel { get; init; } = string.Empty;
}

/// <summary>
/// Result of a deprecation check for a specific code value (US_049 EC-1).
/// </summary>
public sealed record DeprecationCheckResult
{
    /// <summary><c>true</c> when the code is no longer active in the current code library.</summary>
    public bool IsDeprecated { get; init; }

    /// <summary>Human-readable notice to display when the code is deprecated.</summary>
    public string NoticeText { get; init; } = string.Empty;

    /// <summary>
    /// Suggested replacement code values from the library.
    /// May be empty when no direct replacement exists.
    /// </summary>
    public IReadOnlyList<string> ReplacementCodes { get; init; } = [];
}

/// <summary>
/// A single code library search hit returned by the override code-search workflow (US_049 AC-3).
/// </summary>
public sealed record CodeSearchResult
{
    /// <summary>Code value (e.g. "J18.9" or "99213").</summary>
    public string CodeValue { get; init; } = string.Empty;

    /// <summary>Clinical description of the code.</summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>Category label from the code library.</summary>
    public string Category { get; init; } = string.Empty;
}

/// <summary>
/// A single immutable audit trail entry for a <see cref="MedicalCode"/> (US_049 AC-4).
/// </summary>
public sealed record CodingAuditLogEntry
{
    public Guid LogId { get; init; }

    /// <summary>The type of staff action that occurred.</summary>
    public CodingAuditAction Action { get; init; }

    /// <summary>Code value before this action.</summary>
    public string OldCodeValue { get; init; } = string.Empty;

    /// <summary>Code value after this action.</summary>
    public string NewCodeValue { get; init; } = string.Empty;

    /// <summary>Override justification text; <c>null</c> for approval events.</summary>
    public string? Justification { get; init; }

    /// <summary>ID of the staff member who performed the action; <c>null</c> if user was deleted.</summary>
    public Guid? UserId { get; init; }

    /// <summary>UTC timestamp when the action occurred.</summary>
    public DateTimeOffset Timestamp { get; init; }
}

// ─────────────────────────────────────────────────────────────────────────────
// Business exception
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Thrown when staff attempts to approve a code that the library has marked as deprecated.
/// The caller (controller) should return HTTP 422 with the <see cref="DeprecationCheckResult"/>
/// payload so the UI can display the deprecation notice and replacement suggestions (EC-1).
/// </summary>
public sealed class DeprecatedCodeException : InvalidOperationException
{
    public DeprecationCheckResult DeprecationResult { get; }

    public DeprecatedCodeException(DeprecationCheckResult result)
        : base($"Code '{result.NoticeText}' is deprecated and cannot be approved.")
    {
        DeprecationResult = result;
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Interface
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Orchestrates the full staff verification lifecycle for AI-generated medical codes
/// (US_049, AC-1 through AC-4, EC-1, EC-2, FR-064, AIR-009).
///
/// Flow:
/// <list type="number">
///   <item>Staff views verification queue — <see cref="GetVerificationQueueAsync"/>.</item>
///   <item>Staff approves a code — <see cref="ApproveCodeAsync"/> (blocks deprecated codes).</item>
///   <item>Staff overrides a code — <see cref="OverrideCodeAsync"/> with justification.</item>
///   <item>All state transitions write an immutable <see cref="CodingAuditLog"/> row atomically.</item>
///   <item>Progress indicator derives from <see cref="GetVerificationProgressAsync"/>.</item>
/// </list>
/// </summary>
public interface ICodeVerificationService
{
    /// <summary>
    /// Returns all <see cref="CodeVerificationStatus.Pending"/> <see cref="MedicalCode"/> records
    /// for the patient enriched with the fields staff need to make a review decision (AC-1).
    /// Results are ordered by <c>CreatedAt</c> descending.
    /// </summary>
    Task<IReadOnlyList<VerificationQueueItem>> GetVerificationQueueAsync(
        Guid              patientId,
        CancellationToken ct = default);

    /// <summary>
    /// Approves the AI-suggested code: sets <see cref="CodeVerificationStatus.Verified"/>,
    /// records staff attribution and timestamp, and writes an immutable
    /// <see cref="CodingAuditLog"/> entry with <see cref="CodingAuditAction.Approved"/> (AC-2, AC-4).
    /// </summary>
    /// <exception cref="KeyNotFoundException">Code not found.</exception>
    /// <exception cref="DeprecatedCodeException">Code is deprecated in the current library (EC-1).</exception>
    Task<MedicalCode> ApproveCodeAsync(
        Guid              codeId,
        Guid              userId,
        string            correlationId,
        CancellationToken ct = default);

    /// <summary>
    /// Overrides the AI-suggested code with a staff-selected replacement value.
    /// Stores the original code value, applies the new value and description, records the
    /// justification, and writes an immutable <see cref="CodingAuditLog"/> entry with
    /// <see cref="CodingAuditAction.Overridden"/> (AC-3, AC-4).
    /// </summary>
    /// <param name="justification">Required free-text reason; minimum 10 characters.</param>
    /// <exception cref="KeyNotFoundException">Code not found.</exception>
    /// <exception cref="ArgumentException">Justification is too short or code format is invalid.</exception>
    Task<MedicalCode> OverrideCodeAsync(
        Guid              codeId,
        Guid              userId,
        string            newCodeValue,
        string            newDescription,
        string            justification,
        string            correlationId,
        CancellationToken ct = default);

    /// <summary>
    /// Checks whether <paramref name="codeValue"/> is deprecated in the current code library.
    /// Returns replacement suggestions when available (EC-1).
    /// </summary>
    Task<DeprecationCheckResult> CheckDeprecatedAsync(
        string            codeValue,
        CodeType          codeType,
        CancellationToken ct = default);

    /// <summary>
    /// Returns total, verified, overridden, and pending code counts for the patient with a
    /// derived status label: <c>"fully verified"</c>, <c>"partially verified"</c>, or
    /// <c>"pending review"</c> (EC-2).
    /// </summary>
    Task<VerificationProgress> GetVerificationProgressAsync(
        Guid              patientId,
        CancellationToken ct = default);

    /// <summary>
    /// Searches the active ICD-10 or CPT code library by code value or description using a
    /// case-insensitive prefix/contains match.  Used by the staff override code-search
    /// interface (AC-3).
    /// </summary>
    /// <param name="limit">Maximum number of results to return (1–50).</param>
    Task<IReadOnlyList<CodeSearchResult>> SearchCodesAsync(
        string            query,
        CodeType          codeType,
        int               limit,
        CancellationToken ct = default);

    /// <summary>
    /// Returns the immutable audit trail for a specific <see cref="MedicalCode"/> ordered by
    /// <see cref="CodingAuditLog.Timestamp"/> descending (AC-4).
    /// </summary>
    Task<IReadOnlyList<CodingAuditLogEntry>> GetAuditTrailAsync(
        Guid              codeId,
        CancellationToken ct = default);

    /// <summary>
    /// Convenience overload used by the deprecation-check endpoint: resolves the
    /// <c>CodeValue</c> and <c>CodeType</c> from the <see cref="MedicalCode"/> row identified
    /// by <paramref name="codeId"/>, then delegates to <see cref="CheckDeprecatedAsync"/>.
    /// Returns <c>null</c> when the code record does not exist (EC-1).
    /// </summary>
    Task<DeprecationCheckResult?> CheckDeprecatedByCodeIdAsync(
        Guid              codeId,
        CancellationToken ct = default);
}
