<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="FluentAssertions" Version="6.12.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.13" />
    <PackageReference Include="Bogus" Version="35.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UPACIP.Contracts\UPACIP.Contracts.csproj" />
    <ProjectReference Include="..\..\src\UPACIP.Service\UPACIP.Service.csproj" />
    <ProjectReference Include="..\..\src\UPACIP.DataAccess\UPACIP.DataAccess.csproj" />
  </ItemGroup>

</Project>
