using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using UPACIP.DataAccess.Entities;

namespace UPACIP.DataAccess.Configurations;

/// <summary>
/// Fluent API configuration for <see cref="EmailVerificationToken"/> (US_012, AC-1, AC-3).
///
/// Configures:
///   - Primary key, column types, and lengths
///   - Index on <see cref="EmailVerificationToken.TokenHash"/> for fast O(log n) token lookup
///   - Index on <see cref="EmailVerificationToken.UserId"/> for per-user token queries
///   - Foreign key to <see cref="ApplicationUser"/> with CASCADE DELETE
///     so tokens are automatically removed when the account is hard-deleted
/// </summary>
public sealed class EmailVerificationTokenConfiguration : IEntityTypeConfiguration<EmailVerificationToken>
{
    public void Configure(EntityTypeBuilder<EmailVerificationToken> builder)
    {
        builder.ToTable("email_verification_tokens");

        builder.HasKey(t => t.Id);
        builder.Property(t => t.Id).ValueGeneratedNever(); // GUID generated by application layer

        // TokenHash: SHA-256 hex digest = 64 chars (lowercase).
        builder.Property(t => t.TokenHash)
            .IsRequired()
            .HasMaxLength(64);

        builder.Property(t => t.ExpiresAt)
            .IsRequired();

        builder.Property(t => t.IsUsed)
            .IsRequired()
            .HasDefaultValue(false);

        builder.Property(t => t.CreatedAt)
            .IsRequired();

        // Index on TokenHash: primary lookup path when validating a verification link.
        builder.HasIndex(t => t.TokenHash)
            .HasDatabaseName("ix_email_verification_tokens_token_hash");

        // Index on UserId: used to fetch and invalidate all tokens for a given user
        // during resend-verification (AC-3 flow).
        builder.HasIndex(t => t.UserId)
            .HasDatabaseName("ix_email_verification_tokens_user_id");

        // FK: cascade delete ensures tokens are purged when the user account is removed.
        // Configured here for clarity (also declared on ApplicationUserConfiguration).
        builder.HasOne(t => t.User)
            .WithMany(u => u.EmailVerificationTokens)
            .HasForeignKey(t => t.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
