/**
 * useAppointmentCalendarDownload — React Query mutation for downloading appointment iCal
 * files (US_025, FR-025).
 *
 * GET /api/appointments/{appointmentId}/calendar → binary .ics (text/calendar)
 *
 * On success: triggers a browser save of the .ics file, named after the booking reference.
 * On failure: surfaces a typed CalendarDownloadError to the caller.
 *
 * Timezone semantics (EC-2):
 *   The downloaded .ics payload uses clinic-timezone semantics as generated by the backend.
 *   This hook NEVER re-computes timezone conversion — that is the backend's responsibility.
 *   The UI continues to display appointment times in the patient's local timezone via
 *   formatLocalDateTime (AppointmentCard).
 *
 * iCal update semantics (AC-3):
 *   The backend stamps each .ics with the appointment's stable UUID as the VEVENT UID.
 *   Subsequent downloads after reschedule carry the same UID, allowing calendar apps to
 *   update (not duplicate) the existing event.
 *
 * Usage:
 *   const { mutate, isLoading, error, reset } = useAppointmentCalendarDownload();
 *   mutate({ appointmentId: 'uuid', bookingReference: 'BK-20260421-ABC123' });
 */

import { useMutation } from '@tanstack/react-query';
import { apiGetBlob, ApiError } from '@/lib/apiClient';

// ─── Types ────────────────────────────────────────────────────────────────────

export type CalendarDownloadOutcome = 'success' | 'not_found' | 'error';

export interface CalendarDownloadError {
  outcome: Exclude<CalendarDownloadOutcome, 'success'>;
  message: string;
  status: number;
}

export interface CalendarDownloadVariables {
  /** UUID of the appointment to generate the iCal file for. */
  appointmentId: string;
  /** Booking reference used to derive the download filename. */
  bookingReference: string;
}

// ─── Message constants ────────────────────────────────────────────────────────

export const CALENDAR_DOWNLOAD_MESSAGES = {
  NOT_FOUND: 'Appointment not found. Please refresh the page and try again.',
  ERROR: 'Unable to download the calendar file. Please try again.',
} as const;

// ─── Download helper ──────────────────────────────────────────────────────────

/**
 * Triggers a browser file-save for a Blob using a temporary anchor element.
 * Revokes the object URL after a short delay to free memory once the browser
 * has initiated the download (MDN Blob API pattern).
 */
function triggerBlobDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  // Appending to body is required for Firefox compatibility.
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Revoke after a tick so the browser has time to initiate the download.
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

// ─── API fn ───────────────────────────────────────────────────────────────────

async function downloadCalendarFile({
  appointmentId,
  bookingReference,
}: CalendarDownloadVariables): Promise<void> {
  try {
    const blob = await apiGetBlob(`/api/appointments/${appointmentId}/calendar`);
    // Booking reference format BK-YYYYMMDD-XXXXXX is alphanumeric+dashes — safe as filename.
    triggerBlobDownload(blob, `appointment-${bookingReference}.ics`);
  } catch (err) {
    if (err instanceof ApiError) {
      if (err.status === 404) {
        const dlError: CalendarDownloadError = {
          outcome: 'not_found',
          message: CALENDAR_DOWNLOAD_MESSAGES.NOT_FOUND,
          status: err.status,
        };
        throw dlError;
      }
      const dlError: CalendarDownloadError = {
        outcome: 'error',
        message: err.message || CALENDAR_DOWNLOAD_MESSAGES.ERROR,
        status: err.status,
      };
      throw dlError;
    }
    // Network failure or other non-ApiError
    const dlError: CalendarDownloadError = {
      outcome: 'error',
      message: CALENDAR_DOWNLOAD_MESSAGES.ERROR,
      status: 0,
    };
    throw dlError;
  }
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

export function useAppointmentCalendarDownload() {
  return useMutation<void, CalendarDownloadError, CalendarDownloadVariables>({
    mutationFn: downloadCalendarFile,
  });
}
