using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Text;
using UPACIP.DataAccess;
using UPACIP.DataAccess.Entities;
using UPACIP.DataAccess.Enums;
using UPACIP.Service.Caching;

namespace UPACIP.Service.Auth;

/// <summary>
/// Core business logic for the patient self-registration flow (US_012).
///
/// Security design (OWASP / NFR compliance):
///   - Duplicate email check always returns a generic message (AC-4 / OWASP A07).
///   - Password is hashed by ASP.NET Core Identity via <see cref="BcryptPasswordHasher"/> (NFR-013).
///   - Email verification tokens are generated by Identity's
///     <see cref="UserManager{TUser}.GenerateEmailConfirmationTokenAsync"/> and are
///     Base64Url-encoded before inclusion in URLs to prevent encoding issues.
///   - Token expiry (1 hour) is enforced via a separate expiry timestamp stored in the
///     user's custom claim set because the default Identity token provider does not
///     expose expiry separately.  We store the UTC expiry time in a user claim
///     "email_token_expiry" and validate it on verification.
///   - Resend rate limiting uses Redis with a sliding 5-minute TTL (edge case).
///   - All registration/verification events are appended to the AuditLog (NFR-012).
/// </summary>
public sealed class RegistrationService : IRegistrationService
{
    // Redis key prefix for resend rate-limiting counters
    private const string ResendRateLimitKeyPrefix = "reg:resend:";
    private const int MaxResendPerWindow = 3;
    private static readonly TimeSpan ResendWindow = TimeSpan.FromMinutes(5);

    // Custom claim type for email verification token expiry
    private const string EmailTokenExpiryClaim = "email_token_expiry";

    private readonly UserManager<ApplicationUser> _userManager;
    private readonly ApplicationDbContext _db;
    private readonly IEmailService _emailService;
    private readonly ICacheService _cache;
    private readonly IConfiguration _configuration;
    private readonly ILogger<RegistrationService> _logger;

    public RegistrationService(
        UserManager<ApplicationUser> userManager,
        ApplicationDbContext db,
        IEmailService emailService,
        ICacheService cache,
        IConfiguration configuration,
        ILogger<RegistrationService> logger)
    {
        _userManager   = userManager;
        _db            = db;
        _emailService  = emailService;
        _cache         = cache;
        _configuration = configuration;
        _logger        = logger;
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Register
    // ──────────────────────────────────────────────────────────────────────────

    public async Task<RegistrationResult> RegisterAsync(
        RegistrationRequest request,
        string requestIpAddress,
        CancellationToken cancellationToken = default)
    {
        // AC-4: Check email uniqueness without revealing verification status.
        var existing = await _userManager.FindByEmailAsync(request.Email);
        if (existing is not null)
        {
            _logger.LogInformation(
                "Registration attempt with already-registered email {Email}.", request.Email);
            return new RegistrationResult(false, "An account with this email already exists.");
        }

        // Build Identity user — DateOfBirth, FirstName, LastName, and FullName are UPACIP extensions.
        var user = new ApplicationUser
        {
            UserName      = request.Email,
            Email         = request.Email,
            FirstName     = request.FirstName.Trim(),
            LastName      = request.LastName.Trim(),
            FullName      = $"{request.FirstName.Trim()} {request.LastName.Trim()}",
            PhoneNumber   = request.Phone,
            DateOfBirth   = DateOnly.TryParse(request.DateOfBirth, out var dob) ? dob : null,
            AccountStatus = UPACIP.DataAccess.Enums.AccountStatus.PendingVerification,
        };

        // Identity CreateAsync uses the registered IPasswordHasher (BCrypt, work factor 10).
        var createResult = await _userManager.CreateAsync(user, request.Password);
        if (!createResult.Succeeded)
        {
            var errors = MapIdentityErrors(createResult.Errors);
            _logger.LogWarning(
                "Registration failed for {Email}: {Errors}",
                request.Email,
                string.Join(", ", createResult.Errors.Select(e => e.Description)));
            return new RegistrationResult(false, "Registration failed.", errors);
        }

        // Assign the "Patient" role (RBAC — patients are distinguished from Staff/Admin).
        await _userManager.AddToRoleAsync(user, "Patient");

        // Store verification token expiry as a user claim (1-hour window, AC-3).
        var expiry = DateTimeOffset.UtcNow.AddHours(1);
        await _userManager.AddClaimAsync(
            user,
            new System.Security.Claims.Claim(EmailTokenExpiryClaim, expiry.ToString("O")));

        // Generate confirmation token and encode it for URL safety.
        var rawToken       = await _userManager.GenerateEmailConfirmationTokenAsync(user);
        var encodedToken   = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(rawToken));
        var verificationLink = BuildVerificationLink(encodedToken, request.Email);

        // Dispatch verification email (Polly retry/circuit breaker inside SmtpEmailService).
        try
        {
            await _emailService.SendVerificationEmailAsync(
                request.Email,
                $"{request.FirstName} {request.LastName}",
                verificationLink,
                cancellationToken);
        }
        catch (Exception ex)
        {
            // Log the failure but do NOT roll back the user — the resend endpoint can retry.
            _logger.LogError(ex,
                "Failed to send verification email for {Email}. "
                + "User was created but email was not dispatched.",
                request.Email);
        }

        // Audit trail (NFR-012): record registration event.
        await AppendAuditLogAsync(user.Id, AuditAction.DataModify, "ApplicationUser", user.Id, requestIpAddress);

        _logger.LogInformation("New patient account created for {Email}.", request.Email);
        return new RegistrationResult(true, "Registration successful. Please verify your email.");
    }

    // ──────────────────────────────────────────────────────────────────────────
    // VerifyEmail
    // ──────────────────────────────────────────────────────────────────────────

    public async Task<VerifyEmailResult> VerifyEmailAsync(
        string token,
        string email,
        CancellationToken cancellationToken = default)
    {
        var user = await _userManager.FindByEmailAsync(email);
        if (user is null)
            return new VerifyEmailResult(VerifyEmailOutcome.Invalid, "Invalid verification link.");

        // Check custom expiry claim before attempting confirmation.
        var claims = await _userManager.GetClaimsAsync(user);
        var expiryClaim = claims.FirstOrDefault(c => c.Type == EmailTokenExpiryClaim);
        if (expiryClaim is not null &&
            DateTimeOffset.TryParse(expiryClaim.Value, out var expiryUtc) &&
            DateTimeOffset.UtcNow > expiryUtc)
        {
            _logger.LogInformation("Expired verification token for {Email}.", email);
            return new VerifyEmailResult(VerifyEmailOutcome.Expired, "Link expired.");
        }

        // Decode the Base64Url token back to the raw Identity token.
        string rawToken;
        try
        {
            rawToken = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(token));
        }
        catch
        {
            return new VerifyEmailResult(VerifyEmailOutcome.Invalid, "Invalid verification link.");
        }

        var confirmResult = await _userManager.ConfirmEmailAsync(user, rawToken);
        if (!confirmResult.Succeeded)
        {
            _logger.LogWarning(
                "Email confirmation failed for {Email}: {Errors}",
                email,
                string.Join(", ", confirmResult.Errors.Select(e => e.Description)));
            return new VerifyEmailResult(VerifyEmailOutcome.Invalid, "Invalid verification link.");
        }

        // Remove expiry claim now that email is confirmed.
        if (expiryClaim is not null)
            await _userManager.RemoveClaimAsync(user, expiryClaim);

        // Transition account status to Active (AC-2).
        user.AccountStatus = UPACIP.DataAccess.Enums.AccountStatus.Active;
        user.UpdatedAt     = DateTimeOffset.UtcNow;
        await _userManager.UpdateAsync(user);

        // Audit trail (NFR-012).
        await AppendAuditLogAsync(user.Id, AuditAction.DataModify, "ApplicationUser", user.Id, string.Empty);

        _logger.LogInformation("Email verified for {Email}.", email);
        return new VerifyEmailResult(VerifyEmailOutcome.Success, "Email verified successfully.");
    }

    // ──────────────────────────────────────────────────────────────────────────
    // ResendVerification
    // ──────────────────────────────────────────────────────────────────────────

    public async Task<ResendVerificationResult> ResendVerificationAsync(
        string email,
        string requestIpAddress,
        CancellationToken cancellationToken = default)
    {
        // Rate limit: max 3 resends per 5-minute window per email (edge case).
        var rateLimitKey = $"{ResendRateLimitKeyPrefix}{email.ToLowerInvariant()}";
        var counter      = await _cache.GetAsync<ResendCounter>(rateLimitKey, cancellationToken);

        if (counter is not null && counter.Count >= MaxResendPerWindow)
        {
            _logger.LogWarning("Resend rate limit exceeded for {Email}.", email);
            return new ResendVerificationResult(ResendOutcome.RateLimited,
                "Maximum resend attempts reached. Please try again in 5 minutes.");
        }

        var user = await _userManager.FindByEmailAsync(email);
        // Always increment the counter regardless of user existence to prevent
        // enumeration via timing differences (OWASP A07).
        var newCount = (counter?.Count ?? 0) + 1;
        await _cache.SetAsync(rateLimitKey, new ResendCounter(newCount), ResendWindow, cancellationToken);

        if (user is null)
        {
            // Do not reveal whether the email is registered.
            _logger.LogInformation(
                "Resend requested for unregistered email {Email} (no-op).", email);
            return new ResendVerificationResult(ResendOutcome.Sent,
                "If an account with that email exists, a new verification link has been sent.");
        }

        // AC: already verified accounts — respond with generic success (no-op).
        if (await _userManager.IsEmailConfirmedAsync(user))
        {
            _logger.LogInformation(
                "Resend requested for already-verified account {Email} (no-op).", email);
            return new ResendVerificationResult(ResendOutcome.AlreadyVerified,
                "If an account with that email exists, a new verification link has been sent.");
        }

        // Refresh expiry claim: remove old, add new 1-hour window.
        var claims      = await _userManager.GetClaimsAsync(user);
        var oldExpiry   = claims.FirstOrDefault(c => c.Type == EmailTokenExpiryClaim);
        if (oldExpiry is not null)
            await _userManager.RemoveClaimAsync(user, oldExpiry);

        var newExpiry = DateTimeOffset.UtcNow.AddHours(1);
        await _userManager.AddClaimAsync(
            user,
            new System.Security.Claims.Claim(EmailTokenExpiryClaim, newExpiry.ToString("O")));

        var rawToken       = await _userManager.GenerateEmailConfirmationTokenAsync(user);
        var encodedToken   = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(rawToken));
        var verificationLink = BuildVerificationLink(encodedToken, email);

        try
        {
            await _emailService.SendVerificationEmailAsync(
                email, user.FullName, verificationLink, cancellationToken);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex,
                "Failed to resend verification email for {Email}.", email);
            return new ResendVerificationResult(ResendOutcome.Sent,
                "If an account with that email exists, a new verification link has been sent.");
        }

        // Audit trail (NFR-012).
        await AppendAuditLogAsync(user.Id, AuditAction.DataModify, "ApplicationUser", user.Id, requestIpAddress);

        return new ResendVerificationResult(ResendOutcome.Sent,
            "If an account with that email exists, a new verification link has been sent.");
    }

    // ──────────────────────────────────────────────────────────────────────────
    // CheckEmailAvailability
    // ──────────────────────────────────────────────────────────────────────────

    public async Task<bool> IsEmailAvailableAsync(
        string email,
        CancellationToken cancellationToken = default)
    {
        // FindByEmailAsync is case-insensitive per Identity normaliser.
        var existing = await _userManager.FindByEmailAsync(email);
        return existing is null;
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Private helpers
    // ──────────────────────────────────────────────────────────────────────────

    private string BuildVerificationLink(string encodedToken, string email)
    {
        var baseUrl = _configuration["AppSettings:FrontendBaseUrl"]
                      ?? "http://localhost:3000";
        return $"{baseUrl}/verify-email?token={encodedToken}&email={Uri.EscapeDataString(email)}";
    }

    private async Task AppendAuditLogAsync(
        Guid userId,
        AuditAction action,
        string resourceType,
        Guid resourceId,
        string ipAddress)
    {
        try
        {
            _db.AuditLogs.Add(new AuditLog
            {
                UserId       = userId,
                Action       = action,
                ResourceType = resourceType,
                ResourceId   = resourceId,
                IpAddress    = ipAddress,
                UserAgent    = string.Empty,
            });
            await _db.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            // Audit failure must not break the primary request flow.
            _logger.LogError(ex, "Failed to write audit log for user {UserId}.", userId);
        }
    }

    private static IDictionary<string, string[]> MapIdentityErrors(
        IEnumerable<IdentityError> errors)
    {
        return errors
            .GroupBy(e => e.Code)
            .ToDictionary(
                g => g.Key,
                g => g.Select(e => e.Description).ToArray());
    }
}

/// <summary>Simple counter record stored in Redis for resend rate-limiting.</summary>
internal sealed record ResendCounter(int Count);
