/**
 * AppointmentCalendarAction — reusable "Add to Calendar" affordance (US_025, FR-025).
 *
 * Self-contained component that manages the iCal download lifecycle for a single
 * appointment. Handles loading, error, and retry states so callers remain stateless.
 *
 * Two visual variants:
 *   'icon'     (default) — compact IconButton for appointment card action rows (SCR-005, SCR-007)
 *   'outlined' — full outlined Button with label for standalone views (e.g. BookingSuccessView)
 *
 * Accessibility (NFR-046, UXR-201–205):
 *   - aria-busy reflects loading state
 *   - aria-label describes the action + appointment reference
 *   - Tooltip provides visible hover hint and surfaces error messages with retry guidance
 *   - Visible focus ring inherited from MUI theme
 *   - Minimum 44×44px tap target via MUI default button sizing
 *
 * Edge case EC-1 (manual fallback):
 *   The appointment card's date/time/provider details remain visible regardless of
 *   download outcome — this component never obscures or replaces those details.
 *
 * Edge case EC-2 (timezone):
 *   The .ics payload is generated by the backend with clinic-timezone semantics.
 *   The UI displays appointment times in the patient's local timezone (AppointmentCard).
 *
 * @param appointmentId   UUID of the appointment
 * @param bookingReference  Booking reference used as the download filename suffix
 * @param disabled        When true, prevents download (e.g., non-scheduled status)
 * @param variant         'icon' | 'outlined' — visual rendering mode
 */

import { useCallback } from 'react';
import CalendarMonthOutlinedIcon from '@mui/icons-material/CalendarMonthOutlined';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import CircularProgress from '@mui/material/CircularProgress';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';
import {
  useAppointmentCalendarDownload,
} from '@/hooks/useAppointmentCalendarDownload';

// ─── Types ────────────────────────────────────────────────────────────────────

interface Props {
  appointmentId: string;
  bookingReference: string;
  /**
   * Prevents the download action when true.
   * Use for appointments that are not in an eligible state (e.g. Cancelled, Completed).
   */
  disabled?: boolean;
  /**
   * 'icon'     — compact IconButton, suitable for appointment card action rows (default)
   * 'outlined' — full outlined Button with label, suitable for standalone confirmation views
   */
  variant?: 'icon' | 'outlined';
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function AppointmentCalendarAction({
  appointmentId,
  bookingReference,
  disabled = false,
  variant = 'icon',
}: Props) {
  const { mutate, isLoading, error, reset } = useAppointmentCalendarDownload();

  const handleClick = useCallback(() => {
    if (isLoading || disabled) return;
    // Reset previous error before retrying so the mutation state is clean.
    if (error) reset();
    mutate({ appointmentId, bookingReference });
  }, [mutate, reset, isLoading, disabled, error, appointmentId, bookingReference]);

  // ─── Tooltip content ────────────────────────────────────────────────────────
  const tooltipTitle = isLoading
    ? 'Downloading calendar file…'
    : error
    ? `${error.message} Click to retry.`
    : disabled
    ? 'Calendar download is not available for this appointment'
    : 'Add to Calendar';

  // ─── ARIA label ─────────────────────────────────────────────────────────────
  const ariaLabel = isLoading
    ? `Downloading calendar file for appointment ${bookingReference}`
    : error
    ? `Calendar download failed for ${bookingReference}. Click to retry.`
    : disabled
    ? `Add to Calendar not available for appointment ${bookingReference}`
    : `Add appointment ${bookingReference} to calendar`;

  // ─── Shared icon element ────────────────────────────────────────────────────
  const iconElement = isLoading ? (
    <CircularProgress size={16} color="inherit" aria-hidden="true" />
  ) : (
    <CalendarMonthOutlinedIcon fontSize="small" aria-hidden="true" />
  );

  // ─── Outlined Button variant (BookingSuccessView) ───────────────────────────
  if (variant === 'outlined') {
    return (
      <Tooltip title={tooltipTitle} arrow>
        {/* Box wrapper required by Tooltip when button may be disabled */}
        <Box component="span" sx={{ display: 'inline-flex' }}>
          <Button
            variant="outlined"
            disabled={disabled || isLoading}
            onClick={handleClick}
            aria-label={ariaLabel}
            aria-busy={isLoading}
            startIcon={iconElement}
            color={error ? 'error' : 'primary'}
          >
            {isLoading ? 'Downloading…' : 'Add to Calendar'}
          </Button>
        </Box>
      </Tooltip>
    );
  }

  // ─── Icon Button variant (AppointmentCard action row) ───────────────────────
  return (
    <Tooltip title={tooltipTitle} arrow>
      {/* span wrapper required by Tooltip when button may be disabled */}
      <span>
        <IconButton
          size="small"
          disabled={disabled || isLoading}
          onClick={handleClick}
          aria-label={ariaLabel}
          aria-busy={isLoading}
          sx={{
            color: error
              ? 'error.main'
              : disabled
              ? 'text.disabled'
              : 'primary.main',
            '&:hover':
              !disabled && !isLoading && !error
                ? { bgcolor: 'primary.50', color: 'primary.dark' }
                : !disabled && !isLoading && error
                ? { bgcolor: 'error.light', color: 'error.dark' }
                : undefined,
          }}
        >
          {iconElement}
        </IconButton>
      </span>
    </Tooltip>
  );
}
