using UPACIP.DataAccess.Enums;

namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Alert record generated when an AI metric breaches its configured threshold (US_072 task_001, AC-4).
///
/// <para>
/// One row is appended each time the daily calculation detects a metric below its target.
/// The record captures the metric name, current and target values, and the trend direction
/// to give the administrator actionable context.
/// </para>
///
/// <para>
/// Does NOT extend <see cref="BaseEntity"/> because <c>AlertId</c> is the dedicated PK
/// and <c>UpdatedAt</c> has no semantic meaning for alert records — acknowledgement is
/// tracked through <see cref="IsAcknowledged"/> and <see cref="AcknowledgedByUserId"/>.
/// Pattern follows <see cref="AuditLog"/>.
/// </para>
/// </summary>
public sealed class AiMetricAlert
{
    /// <summary>Surrogate UUID primary key — generated by the application layer.</summary>
    public Guid AlertId { get; set; } = Guid.NewGuid();

    /// <summary>UTC timestamp when this alert was generated by the daily calculation run.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Name of the metric that breached its threshold.
    /// Matches the <see cref="AiMetricThreshold.MetricName"/> value for correlation.
    /// Max length 100 characters.
    /// </summary>
    public string MetricName { get; set; } = string.Empty;

    /// <summary>
    /// Measured value of the metric at the time the alert was generated.
    /// For accuracy metrics: percentage in [0, 100].
    /// For latency metrics: milliseconds.
    /// </summary>
    public double CurrentValue { get; set; }

    /// <summary>
    /// Configured target threshold at the time the alert was generated.
    /// Snapshot stored here so historical alerts remain accurate even if the threshold changes.
    /// </summary>
    public double TargetValue { get; set; }

    /// <summary>
    /// Direction the metric was trending when the alert was generated (AC-4).
    /// </summary>
    public TrendDirection TrendDirection { get; set; }

    /// <summary>
    /// <c>true</c> once an administrator has reviewed and acknowledged this alert.
    /// </summary>
    public bool IsAcknowledged { get; set; }

    /// <summary>
    /// Foreign key to <c>ApplicationUser</c> who acknowledged this alert.
    /// <c>null</c> until the alert is acknowledged.
    /// </summary>
    public Guid? AcknowledgedByUserId { get; set; }

    /// <summary>Navigation property to the acknowledging user. Null until acknowledged.</summary>
    public ApplicationUser? AcknowledgedBy { get; set; }
}
