using UPACIP.DataAccess.Enums;

namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Immutable per-request AI cost record appended after every AI Gateway call (US_071 TASK_001, AC-1).
///
/// <para>
/// Stores the raw cost signals needed by the daily aggregation job
/// (<c>AiCostDailySummary</c>) and the budget-threshold alert service:
/// <list type="bullet">
///   <item><see cref="Provider"/> and <see cref="RequestType"/> — dimension keys for aggregation.</item>
///   <item><see cref="InputTokens"/> / <see cref="OutputTokens"/> — raw token usage.</item>
///   <item><see cref="EstimatedCost"/> — USD cost; either actual (from provider API) or
///         approximate (from <see cref="AiCostBudgetConfig"/> rate card).</item>
///   <item><see cref="CostSource"/> — flags approximate entries for downstream consumers.</item>
///   <item><see cref="CorrelationId"/> — ties the cost record back to the originating
///         HTTP request for cross-service tracing (TR-028).</item>
/// </list>
/// </para>
///
/// <para>
/// Does NOT extend <see cref="BaseEntity"/> because this table is append-only
/// (no <c>UpdatedAt</c> is ever set).  Pattern follows <see cref="AuditLog"/>.
/// </para>
///
/// Append-only: no UPDATE or DELETE operations are permitted on this table.
/// </summary>
public sealed class AiRequestLog
{
    /// <summary>Surrogate UUID primary key — generated by the application layer.</summary>
    public Guid LogId { get; set; } = Guid.NewGuid();

    /// <summary>AI provider that processed the request (e.g., OpenAI or Anthropic).</summary>
    public AiProvider Provider { get; set; }

    /// <summary>
    /// AI operation type — determines which token budget and rate card apply.
    /// Maps to <c>UPACIP.Api.Features.AIGateway.Contracts.AIRequestType</c>.
    /// </summary>
    public AiRequestType RequestType { get; set; }

    /// <summary>Number of input (prompt) tokens consumed by this request.</summary>
    public int InputTokens { get; set; }

    /// <summary>Number of output (completion) tokens produced by this request.</summary>
    public int OutputTokens { get; set; }

    /// <summary>
    /// Estimated cost in USD for this request.
    /// Sourced from the provider API when available; otherwise calculated from
    /// <c>InputTokens</c> and <c>OutputTokens</c> multiplied by
    /// <see cref="AiCostBudgetConfig.CostPer1kInputTokens"/> /
    /// <see cref="AiCostBudgetConfig.CostPer1kOutputTokens"/>.
    /// Precision: <c>numeric(12,6)</c> — supports up to $999,999.999999 per request.
    /// </summary>
    public decimal EstimatedCost { get; set; }

    /// <summary>
    /// Indicates whether <see cref="EstimatedCost"/> was reported by the provider API
    /// (<c>Actual</c>) or estimated via the rate card (<c>Approximate</c>).
    /// </summary>
    public AiCostSource CostSource { get; set; }

    /// <summary>
    /// Correlation ID from the originating HTTP request (TR-028, <c>X-Correlation-ID</c> header).
    /// Used for cross-service tracing — joins this cost record to the AI Gateway
    /// request log and the originating application request.
    /// </summary>
    public Guid CorrelationId { get; set; }

    /// <summary>UTC timestamp when this record was persisted. Immutable after insert.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
