namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Lightweight reference stub that is retained in the main schema after a full
/// <see cref="Appointment"/> record has been moved to <c>archive.appointments</c>.
///
/// Purpose (US_086 AC-3, AC-5, DR-018, DR-020):
/// <list type="bullet">
///   <item>
///     Keeps the original appointment ID, patient ID, and appointment time visible to
///     patient-history queries without requiring a cross-schema archive lookup on every request.
///   </item>
///   <item>
///     Patient history endpoints can render the appointment on the timeline and offer a
///     "view archived details" action that fetches the full record from <c>archive.appointments</c>
///     via <see cref="IAppointmentArchivalService.GetArchivedAppointmentAsync"/>.
///   </item>
/// </list>
///
/// <c>Id</c> is intentionally set to the same value as the original <see cref="Appointment.Id"/>
/// so that cross-reference queries are a simple PK lookup.  There is no FK constraint from this
/// column to the <c>appointments</c> table — that constraint would prevent the delete that triggers
/// archival.
/// </summary>
public sealed class ArchivedAppointmentReference
{
    /// <summary>
    /// Same value as the original <see cref="Appointment.Id"/>.
    /// Set by the application layer; never auto-generated by the database.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>FK to <see cref="Patient"/> — maintained for patient-history queries.</summary>
    public Guid PatientId { get; set; }

    /// <summary>
    /// Original UTC appointment time.
    /// Stored here so patient-timeline UIs can display it without an archive round-trip.
    /// </summary>
    public DateTime AppointmentTime { get; set; }

    /// <summary>
    /// Appointment status at the time of archival (e.g. "Completed", "Cancelled").
    /// Max 20 characters — matches the <c>Status</c> column of the <c>appointments</c> table.
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the archival job moved the record to the archive schema.</summary>
    public DateTime ArchivedAtUtc { get; set; }

    /// <summary>
    /// Identifies the archive table where the full appointment record can be found.
    /// Always <c>"archive.appointments"</c> in the current schema.
    /// Stored to support future archive-schema evolution without breaking lookup paths.
    /// Max 100 characters.
    /// </summary>
    public string ArchiveTable { get; set; } = "archive.appointments";

    // ── Navigation ────────────────────────────────────────────────────────────

    /// <summary>Navigation to the owning patient.  Null until explicitly loaded.</summary>
    public Patient Patient { get; set; } = null!;
}
