namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Lightweight reference stub retained in the main schema after a full
/// <see cref="Patient"/> record (and all its dependent data) has been moved to
/// <c>archive.patients</c> (US_087 AC-4, DR-021).
///
/// Purpose:
/// <list type="bullet">
///   <item>
///     Allows audit log entries that reference the original patient ID
///     (via <see cref="AuditLog.ResourceId"/>) to still resolve to a meaningful
///     display name (<see cref="FullName"/>) without requiring a cross-schema lookup.
///   </item>
///   <item>
///     Provides a lightweight "is this patient archived?" check for API callers
///     (e.g. returning HTTP 410 Gone instead of 404 Not Found).
///   </item>
/// </list>
///
/// <c>Id</c> holds the same value as the original <c>patients.Id</c> so that any
/// cross-system reference to the patient ID remains valid.  There is intentionally no
/// FK constraint back to the <c>patients</c> table — the original patient row no longer
/// exists after archival.
/// </summary>
public sealed class ArchivedPatientReference
{
    /// <summary>
    /// Same value as the original <see cref="Patient.Id"/>.
    /// Set by the application layer; never auto-generated by the database.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Patient's full display name at the time of archival.
    /// Preserved for audit log resolution without requiring an archive lookup.
    /// Max 200 characters — matches the <c>patients.FullName</c> column.
    /// </summary>
    public string FullName { get; set; } = string.Empty;

    /// <summary>
    /// Patient's email address at the time of archival.
    /// Preserved for identity disambiguation.
    /// Max 256 characters — matches the <c>patients.Email</c> column.
    /// </summary>
    public string Email { get; set; } = string.Empty;

    /// <summary>UTC timestamp when the patient was originally soft-deleted.</summary>
    public DateTime DeletedAtUtc { get; set; }

    /// <summary>UTC timestamp when the archival job moved the patient to the archive schema.</summary>
    public DateTime ArchivedAtUtc { get; set; }

    /// <summary>
    /// PostgreSQL schema where the full patient record can be found.
    /// Always <c>"archive"</c> in the current deployment.
    /// Stored to support future schema evolution without breaking lookup paths.
    /// Max 50 characters.
    /// </summary>
    public string ArchiveSchema { get; set; } = "archive";
}
