namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Persistent audit record for each backup attempt written to the <c>backup_logs</c>
/// table (US_088, AC-3).
///
/// One row is created per backup attempt (initial or retry).  When a retry succeeds
/// after an initial failure, two rows are written: one with <c>Status = "Failed"</c>
/// (<c>WasRetry = false</c>) and one with <c>Status = "Completed"</c>
/// (<c>WasRetry = true</c>).
///
/// When the backup is skipped due to insufficient disk space (edge case 1), a single
/// row is written with <c>Status = "Skipped"</c>.
/// </summary>
public sealed class BackupLog
{
    /// <summary>Primary key — generated by the application (Guid.NewGuid()).</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Backup file name (e.g. <c>upacip_backup_20260428_020000.dump</c>).
    /// Empty string when the backup was skipped or the file was never written.
    /// Max 300 characters.
    /// </summary>
    public string FileName { get; set; } = string.Empty;

    /// <summary>
    /// Backup file size in bytes at the time of checksum computation.
    /// Zero for skipped or failed attempts.
    /// </summary>
    public long FileSizeBytes { get; set; }

    /// <summary>Wall-clock duration of the <c>pg_dump</c> process.</summary>
    public TimeSpan Duration { get; set; }

    /// <summary>
    /// Outcome of this attempt: <c>"Completed"</c>, <c>"Failed"</c>, or <c>"Skipped"</c>.
    /// Max 20 characters.
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>
    /// SHA-256 hex checksum of the backup file (AC-3).
    /// Empty string for failed or skipped attempts.
    /// Max 64 characters (hex-encoded SHA-256).
    /// </summary>
    public string Checksum { get; set; } = string.Empty;

    /// <summary>
    /// Human-readable failure reason (<c>pg_dump</c> stderr or disk-space message).
    /// <c>null</c> for successful backups.
    /// Max 2 000 characters.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// <c>true</c> when this was a retry attempt following an initial failure (AC-4).
    /// </summary>
    public bool WasRetry { get; set; }

    /// <summary>UTC timestamp when this log entry was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}
