namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Abstract base class providing common audit fields for all domain entities.
/// Entities that deviate from this pattern (AuditLog, NotificationLog) do NOT inherit
/// from BaseEntity and manage their own primary-key and timestamp fields.
/// </summary>
public abstract class BaseEntity
{
    /// <summary>Surrogate UUID primary key — generated by the application layer.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>UTC timestamp when the record was first persisted.</summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the last write to this record.</summary>
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
