using UPACIP.DataAccess.Enums;

namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Alert record generated when calibration drift exceeds the 5% threshold between
/// predicted and actual accuracy for a clinical data category (US_073 task_001, AC-4).
///
/// <para>
/// One alert is appended per (DataType, CalibrationRunDate) pair where any confidence
/// bin reports <c>DriftPercentage &gt; 5</c>.  The alert surfaces in the admin dashboard
/// for review and acknowledgement.
/// </para>
///
/// <para>
/// Does NOT extend <see cref="BaseEntity"/> because <c>AlertId</c> is the dedicated PK
/// and <c>UpdatedAt</c> has no semantic meaning for append-only alert records.
/// Pattern follows <see cref="AiMetricAlert"/> and <see cref="AuditLog"/>.
/// </para>
/// </summary>
public sealed class CalibrationDriftAlert
{
    /// <summary>Surrogate UUID primary key — generated by the application layer.</summary>
    public Guid AlertId { get; set; } = Guid.NewGuid();

    /// <summary>UTC timestamp when this alert was generated by the calibration job.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Clinical data category for which drift was detected.
    /// </summary>
    public DataType DataType { get; set; }

    /// <summary>
    /// Mean predicted accuracy across drifted bins at the time the alert was generated,
    /// as a percentage (0–100).
    /// </summary>
    public double PredictedAccuracy { get; set; }

    /// <summary>
    /// Measured actual accuracy across drifted bins at the time the alert was generated,
    /// as a percentage (0–100).
    /// </summary>
    public double ActualAccuracy { get; set; }

    /// <summary>
    /// Maximum drift percentage observed across all confidence bins for this
    /// <see cref="DataType"/> in the triggering calibration run.
    /// </summary>
    public double DriftPercentage { get; set; }

    /// <summary>
    /// <c>true</c> once an administrator has reviewed and acknowledged this alert.
    /// </summary>
    public bool IsAcknowledged { get; set; }

    /// <summary>
    /// Foreign key to <c>ApplicationUser</c> who acknowledged this alert.
    /// Null while the alert is unacknowledged.
    /// </summary>
    public Guid? AcknowledgedByUserId { get; set; }

    /// <summary>
    /// UTC timestamp when the alert was acknowledged.
    /// Null while the alert is unacknowledged.
    /// </summary>
    public DateTime? AcknowledgedAt { get; set; }

    // ── Navigation property ───────────────────────────────────────────────────

    /// <summary>Navigation to the acknowledging <c>ApplicationUser</c>. Null while unacknowledged.</summary>
    public ApplicationUser? AcknowledgedBy { get; set; }
}
