using Pgvector;

namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Stores vector embeddings for payer and CMS coding guidelines to support
/// AI-assisted justification retrieval for medical code suggestions (NFR-AI-003).
/// </summary>
public sealed class CodingGuidelineEmbedding
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Code system this guideline belongs to (e.g. "ICD-10-CM", "CPT").</summary>
    public string CodeSystem { get; set; } = string.Empty;

    /// <summary>Specific code value the guideline paragraph relates to (optional).</summary>
    public string? CodeValue { get; set; }

    /// <summary>Full text of the guideline paragraph used to generate the embedding.</summary>
    public string GuidelineText { get; set; } = string.Empty;

    /// <summary>384-dimensional sentence-transformer embedding vector.</summary>
    public Vector Embedding { get; set; } = null!;

    /// <summary>
    /// Full-text search vector generated by PostgreSQL from code_value + guideline_text.
    /// Populated by a GENERATED ALWAYS AS clause; read-only from the application.
    /// </summary>
    public string? ContentTsv { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
