namespace UPACIP.DataAccess.Entities;

/// <summary>
/// A HIPAA compliance gap record created when a technical safeguard check fails (US_093, edge case 1).
/// Tracks the gap lifecycle from identification through remediation with a 30-day deadline.
/// Persisted in <c>compliance_gaps</c>.
/// </summary>
public sealed class ComplianceGap
{
    /// <summary>Primary key — generated by the application.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Foreign key to the <see cref="ComplianceVerificationLog"/> that identified this gap.</summary>
    public Guid VerificationLogId { get; set; }

    /// <summary>Navigation property to the parent verification log.</summary>
    public ComplianceVerificationLog? VerificationLog { get; set; }

    /// <summary>Name of the control that failed (e.g. "Encryption at Rest (AES-256)").</summary>
    public required string ControlName { get; set; }

    /// <summary>HIPAA Security Rule section reference (e.g. "§164.312(a)(2)(iv) — Encryption and Decryption").</summary>
    public required string HipaaReference { get; set; }

    /// <summary>Specific reason the control failed verification.</summary>
    public required string FailureReason { get; set; }

    /// <summary>Auto-generated remediation guidance for the identified gap.</summary>
    public required string RemediationPlan { get; set; }

    /// <summary>UTC timestamp when the gap was identified.</summary>
    public DateTime IdentifiedAtUtc { get; set; }

    /// <summary>
    /// Target date for remediation — defaults to 30 days from identification
    /// per HIPAA audit gap response policy (US_093 edge case 1).
    /// </summary>
    public DateTime RemediationDeadlineUtc { get; set; }

    /// <summary>Lifecycle status: "Open", "InProgress", or "Remediated".</summary>
    public required string Status { get; set; }

    /// <summary>UTC timestamp when the gap was closed. Null while open or in progress.</summary>
    public DateTime? RemediatedAtUtc { get; set; }
}
