namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Versioned compliance policy document supporting HIPAA administrative safeguards
/// (US_093, AC-2, §164.308(a)(1)).
///
/// <para>
/// Stores security policies, staff training requirements, and incident response procedures
/// as database-backed records that can be queried during HIPAA audits to demonstrate
/// evidence of documented and accessible safeguards.
/// </para>
///
/// <para>Versioning model:</para>
/// <list type="bullet">
///   <item>New versions create new rows; old versions are retained for the audit trail.</item>
///   <item>Only one row per (PolicyType + Title) may have <c>Status = "Active"</c>.</item>
///   <item>When a new version is approved, the previous active version transitions to "Superseded".</item>
/// </list>
///
/// Table: <c>compliance_policies</c>
/// </summary>
public sealed class CompliancePolicy
{
    /// <summary>Primary key — generated by the application.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Policy category discriminator.
    /// Values: "SecurityPolicy", "TrainingRequirement", "IncidentResponseProcedure".
    /// </summary>
    public required string PolicyType { get; set; }

    /// <summary>Human-readable policy title (e.g., "PHI Access Control Policy").</summary>
    public required string Title { get; set; }

    /// <summary>Full policy content in Markdown format for rich rendering.</summary>
    public required string Content { get; set; }

    /// <summary>
    /// Monotonically increasing version counter.
    /// Assigned by <c>CompliancePolicyService</c>: 1 for new policies, max+1 for revisions.
    /// </summary>
    public int Version { get; set; }

    /// <summary>
    /// HIPAA section this policy addresses (e.g., "§164.308(a)(1) — Security Management Process").
    /// </summary>
    public required string HipaaReference { get; set; }

    /// <summary>
    /// Lifecycle status.
    /// Values: "Draft", "Active", "Superseded", "Archived".
    /// </summary>
    public required string Status { get; set; }

    /// <summary>Admin user who created this version.</summary>
    public required string CreatedBy { get; set; }

    /// <summary>Compliance officer who approved this version; null until approved.</summary>
    public string? ApprovedBy { get; set; }

    /// <summary>UTC timestamp when this version was created.</summary>
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>UTC timestamp when this version was approved; null until approved.</summary>
    public DateTime? ApprovedAtUtc { get; set; }

    /// <summary>
    /// UTC date when the policy becomes enforceable; null until approved.
    /// Typically set equal to <c>ApprovedAtUtc</c>.
    /// </summary>
    public DateTime? EffectiveDate { get; set; }

    /// <summary>
    /// UTC date when the policy must be reviewed and renewed.
    /// Compliance officers set this at approval time (e.g., 1 year from approval).
    /// </summary>
    public DateTime? ExpirationDate { get; set; }
}
