namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Audit trail record for a HIPAA technical safeguard verification run (US_093, AC-1).
/// Each row is append-only — persisted in <c>compliance_verification_logs</c>.
/// Provides auditable proof of continuous technical safeguard enforcement (NFR-041, NFR-042).
/// </summary>
public sealed class ComplianceVerificationLog
{
    /// <summary>Primary key — generated by the application.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>UTC timestamp when the verification was executed.</summary>
    public DateTime ExecutedAtUtc { get; set; }

    /// <summary>Admin user who triggered the verification run.</summary>
    public required string ExecutedBy { get; set; }

    /// <summary>Total number of controls verified.</summary>
    public int TotalChecks { get; set; }

    /// <summary>Number of controls that passed verification.</summary>
    public int PassedChecks { get; set; }

    /// <summary>Number of controls that failed verification.</summary>
    public int FailedChecks { get; set; }

    /// <summary>Overall status: "AllPassed" or "HasGaps".</summary>
    public required string Status { get; set; }

    /// <summary>JSON-serialized full compliance verification report for audit evidence.</summary>
    public required string ReportJson { get; set; }

    /// <summary>Navigation property: compliance gaps created from this verification run.</summary>
    public ICollection<ComplianceGap> Gaps { get; set; } = new List<ComplianceGap>();
}
