namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Configurable compliance evaluation rule with JSON-based evaluation criteria
/// (US_093, AC-2 edge case 2 — rules updatable without code changes).
///
/// <para>
/// Compliance officers can add or update rules (e.g., for new HIPAA regulations) via the
/// <c>POST /api/admin/compliance/rules</c> endpoint without requiring a code deployment.
/// The <see cref="EvaluationCriteriaJson"/> field encodes the rule logic as a JSON object
/// interpreted at runtime by <c>ComplianceRuleEngine</c>.
/// </para>
///
/// <para>Supported evaluation types (via <c>EvaluationCriteriaJson.type</c>):</para>
/// <list type="bullet">
///   <item><c>config_check</c> — Reads an IConfiguration path and compares against an expected value.</item>
///   <item><c>db_query</c>    — Executes a parameterized PostgreSQL query and checks the result count.</item>
///   <item><c>service_check</c> — Verifies a boolean configuration flag is enabled.</item>
/// </list>
///
/// Table: <c>compliance_rules</c>
/// </summary>
public sealed class ComplianceRule
{
    /// <summary>Primary key — generated by the application.</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Unique rule identifier used for upsert and display.
    /// Examples: "SessionTimeout", "PasswordComplexity", "AuditLogRetention".
    /// </summary>
    public required string RuleName { get; set; }

    /// <summary>
    /// Rule classification: "Technical", "Administrative", or "Physical".
    /// </summary>
    public required string Category { get; set; }

    /// <summary>Human-readable description of what the rule verifies.</summary>
    public required string Description { get; set; }

    /// <summary>
    /// JSON object encoding the rule's evaluation logic.
    /// Schema varies by <c>type</c> field:
    /// <code>
    /// config_check:  { "type":"config_check", "configPath":"...", "operator":"&lt;=", "expectedValue":"..." }
    /// db_query:      { "type":"db_query", "query":"SELECT COUNT(*) ...", "operator":"=", "expectedValue":"0" }
    /// service_check: { "type":"service_check", "configPath":"...", "expectedValue":"true" }
    /// </code>
    /// </summary>
    public required string EvaluationCriteriaJson { get; set; }

    /// <summary>Whether this rule is included in automated evaluations (default: true).</summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Impact level if the rule fails: "Critical", "High", "Medium", "Low".
    /// </summary>
    public required string Severity { get; set; }

    /// <summary>
    /// HIPAA section this rule enforces (e.g., "§164.312(a)(2)(iii)").
    /// </summary>
    public required string HipaaReference { get; set; }

    /// <summary>Actionable remediation guidance shown when the rule fails.</summary>
    public string? RemediationGuidance { get; set; }

    /// <summary>UTC timestamp when the rule was first created.</summary>
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>UTC timestamp of the most recent update (set on upsert).</summary>
    public DateTime UpdatedAtUtc { get; set; }
}
