namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Versioned, step-by-step disaster recovery procedure document (US_095, AC-3, DR-026).
///
/// Each runbook covers a specific failure scenario (e.g., full database loss) and
/// contains an ordered list of recovery steps with estimated time-to-completion per step.
/// The sum of all step estimates must not exceed the RTO target (240 minutes / 4 hours)
/// per NFR-025.
///
/// Runbooks are versioned — when an existing runbook is updated, the version number is
/// incremented and the previous Active record is archived.
///
/// <para>
/// <b>StepsJson schema</b> (JSON array of step objects):
/// <code>
/// [
///   { "stepNumber": 1, "action": "Identify failure scope", "estimatedMinutes": 15, "responsible": "DBA" },
///   ...
/// ]
/// </code>
/// </para>
/// </summary>
public sealed class DisasterRecoveryRunbook
{
    /// <summary>Primary key — generated by the application (Guid.NewGuid()).</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Human-readable runbook title, e.g. "Full Database Recovery Procedure".
    /// Max 200 characters.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Failure scenario this runbook covers:
    /// FullDatabaseLoss | PartialDataCorruption | ServiceOutage | SecurityBreach.
    /// Max 50 characters.
    /// </summary>
    public string ScenarioType { get; set; } = string.Empty;

    /// <summary>
    /// JSON-serialized array of recovery steps. Each step object has the shape:
    /// <code>{ "stepNumber": int, "action": string, "estimatedMinutes": int, "responsible": string }</code>
    /// Stored as a text column (no EF Core JSON mapping required).
    /// </summary>
    public string StepsJson { get; set; } = "[]";

    /// <summary>
    /// Sum of all step <c>estimatedMinutes</c> values. Must be ≤ the configured RTO target
    /// (default 240 minutes). Validated by the API before persisting. (NFR-025)
    /// </summary>
    public int TotalEstimatedMinutes { get; set; }

    /// <summary>
    /// Runbook lifecycle status: Draft | Active | Archived.
    /// Max 20 characters.
    /// </summary>
    public string Status { get; set; } = "Draft";

    /// <summary>Monotonically increasing version number. Starts at 1; incremented on each update.</summary>
    public int Version { get; set; } = 1;

    /// <summary>Identity of the administrator who created this runbook.</summary>
    public string CreatedBy { get; set; } = string.Empty;

    /// <summary>UTC timestamp when this runbook was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

    /// <summary>UTC timestamp of the most recent update to this runbook.</summary>
    public DateTime UpdatedAtUtc { get; set; } = DateTime.UtcNow;
}
