namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Critical alert record generated when the daily hallucination rate exceeds the 5%
/// target threshold (US_074 task_002, AC-2, AIR-Q06).
///
/// <para>
/// Alerts are also generated retroactively when staff discover hallucinations in
/// previously-approved entries (edge case); in that case <see cref="IsRetroactive"/>
/// is set to <c>true</c>.
/// </para>
///
/// <para>
/// Does NOT extend <see cref="BaseEntity"/> — uses a dedicated <see cref="AlertId"/> PK
/// and append-only semantics, following the pattern of <see cref="CalibrationDriftAlert"/>
/// and <see cref="AiMetricAlert"/>.
/// </para>
/// </summary>
public sealed class HallucinationAlert
{
    /// <summary>Surrogate UUID primary key — generated by the application layer.</summary>
    public Guid AlertId { get; set; } = Guid.NewGuid();

    /// <summary>UTC timestamp when this alert was generated by the aggregation job or retroactive detection.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Actual hallucination rate at the time the alert was triggered (0–1 decimal).
    /// </summary>
    public double CurrentRate { get; set; }

    /// <summary>
    /// Target hallucination rate threshold (0.05 = 5 %) per AC-2.
    /// </summary>
    public double TargetRate { get; set; } = 0.05;

    /// <summary>
    /// Human-readable recommendation generated alongside the alert.
    /// Example: "Model review recommended — hallucination rate 8.2% exceeds 5% target.
    /// Review recent model changes and prompt templates."
    /// </summary>
    public string Recommendation { get; set; } = string.Empty;

    /// <summary>
    /// <c>true</c> when this alert was triggered by a retroactive hallucination detection
    /// (staff discovered unsupported data in a previously-approved entry) rather than by
    /// the daily aggregation job.
    /// </summary>
    public bool IsRetroactive { get; set; }

    /// <summary><c>true</c> once an administrator has reviewed and acknowledged this alert.</summary>
    public bool IsAcknowledged { get; set; }

    /// <summary>
    /// FK to <see cref="ApplicationUser"/> who acknowledged this alert.
    /// Null while the alert is unacknowledged.
    /// </summary>
    public Guid? AcknowledgedByUserId { get; set; }

    /// <summary>UTC timestamp when the alert was acknowledged. Null while unacknowledged.</summary>
    public DateTime? AcknowledgedAt { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    /// <summary>The user who acknowledged this alert (null until acknowledged).</summary>
    public ApplicationUser? AcknowledgedBy { get; set; }
}
