using Pgvector;

namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Stores vector embeddings for intake form template sections to enable
/// AI-driven conversational intake matching (NFR-AI-002).
/// </summary>
public sealed class IntakeTemplateEmbedding
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Name of the intake template (e.g. "General Adult Intake").</summary>
    public string TemplateName { get; set; } = string.Empty;

    /// <summary>Logical section within the template (e.g. "Chief Complaint").</summary>
    public string? Section { get; set; }

    /// <summary>Full text of the template section content used to generate the embedding.</summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>384-dimensional sentence-transformer embedding vector.</summary>
    public Vector Embedding { get; set; } = null!;

    /// <summary>
    /// Full-text search vector generated by PostgreSQL from template_name + content.
    /// Populated by a GENERATED ALWAYS AS clause; read-only from the application.
    /// </summary>
    public string? ContentTsv { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
