using Pgvector;

namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Stores vector embeddings for medical terminology (ICD-10, CPT, SNOMED)
/// to support context-aware AI medical coding suggestions (NFR-AI-001).
/// </summary>
public sealed class MedicalTerminologyEmbedding
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Human-readable medical term (e.g. "Type 2 Diabetes Mellitus").</summary>
    public string Term { get; set; } = string.Empty;

    /// <summary>Clinical description or definition of the term.</summary>
    public string? Description { get; set; }

    /// <summary>Ontology or data source (e.g. "ICD-10-CM", "SNOMED-CT").</summary>
    public string? Source { get; set; }

    /// <summary>384-dimensional sentence-transformer embedding vector.</summary>
    public Vector Embedding { get; set; } = null!;

    /// <summary>
    /// Full-text search vector generated by PostgreSQL from term + description.
    /// Populated by a GENERATED ALWAYS AS clause; read-only from the application.
    /// </summary>
    public string? ContentTsv { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}
