namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Persistent audit record for each admin-triggered point-in-time recovery operation
/// (US_090 task_002, AC-2, AC-3, DR-027).
///
/// One row per PITR attempt, recording the target timestamp, achieved recovery point,
/// base backup used, WAL segments replayed, and all validation outcomes.
/// </summary>
public sealed class RecoveryLog
{
    /// <summary>Primary key — generated by the application (<c>Guid.NewGuid()</c>).</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>The UTC timestamp that was requested as the recovery target.</summary>
    public DateTime TargetTimestampUtc { get; set; }

    /// <summary>The actual UTC recovery point achieved (may differ due to WAL granularity).</summary>
    public DateTime ActualRecoveryPointUtc { get; set; }

    /// <summary>Filename of the base backup restored as the PITR starting point. Max 300 characters.</summary>
    public string BaseBackupUsed { get; set; } = string.Empty;

    /// <summary>Number of WAL segments replayed from base backup to the target point.</summary>
    public int WalSegmentsReplayed { get; set; }

    /// <summary>True when the full PITR pipeline completed without error.</summary>
    public bool Success { get; set; }

    /// <summary>True when post-recovery integrity validation (row counts + checksums) passed (AC-3).</summary>
    public bool IntegrityPassed { get; set; }

    /// <summary>Elapsed time for the full PITR pipeline.</summary>
    public TimeSpan RecoveryDuration { get; set; }

    /// <summary>
    /// Reason PITR fell back to base backup only (WAL corruption — edge case 1).
    /// Null when WAL replay completed normally.
    /// Max 2000 characters.
    /// </summary>
    public string? FallbackReason { get; set; }

    /// <summary>
    /// Error details when <see cref="Success"/> is false. Null on success.
    /// Max 2000 characters.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>Identity of the admin user who triggered the recovery (sub claim / username). Max 256 characters.</summary>
    public string PerformedBy { get; set; } = string.Empty;

    /// <summary>True when the request was a dry run (pre-flight only — no actual recovery executed).</summary>
    public bool IsDryRun { get; set; }

    /// <summary>UTC timestamp when this recovery log entry was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}
