namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Persistent record of a quarterly disaster recovery restoration test execution
/// (US_095, AC-3, DR-026).
///
/// One row is written per test run. The <see cref="Quarter"/> field links each record
/// to the calendar quarter it satisfies (e.g., "2026-Q2"). The scheduler uses this
/// table to determine whether the current quarter's test obligation has been fulfilled.
/// </summary>
public sealed class RecoveryTestRecord
{
    /// <summary>Primary key — generated by the application (Guid.NewGuid()).</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>UTC timestamp when the test was executed.</summary>
    public DateTime ExecutedAtUtc { get; set; }

    /// <summary>Identity of the administrator who triggered the test.</summary>
    public string ExecutedBy { get; set; } = string.Empty;

    /// <summary>
    /// Test scope:
    /// <list type="bullet">
    ///   <item><term>FullRestoration</term><description>Complete database restore from backup + WAL replay.</description></item>
    ///   <item><term>PartialRestoration</term><description>Selected table restore for targeted data recovery.</description></item>
    ///   <item><term>PITRTest</term><description>Point-in-time recovery to a specific LSN or timestamp.</description></item>
    /// </list>
    /// Max 30 characters.
    /// </summary>
    public string TestType { get; set; } = string.Empty;

    /// <summary>True when the test completed all validation phases successfully.</summary>
    public bool Passed { get; set; }

    /// <summary>
    /// Wall-clock duration of the full restoration pipeline, from test start to completion
    /// of integrity validation. Compared against the configured RTO target (AC-3, NFR-025).
    /// </summary>
    public TimeSpan ActualRecoveryTime { get; set; }

    /// <summary>Number of rows verified during the integrity check phase of the test.</summary>
    public int RowsVerified { get; set; }

    /// <summary>Human-readable failure reason for failed tests; null when passed.</summary>
    public string? FailureReason { get; set; }

    /// <summary>
    /// Calendar quarter this test satisfies, formatted as "YYYY-Qn" (e.g., "2026-Q2").
    /// Max 10 characters.
    /// </summary>
    public string Quarter { get; set; } = string.Empty;

    /// <summary>UTC timestamp when this record was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}
