namespace UPACIP.DataAccess.Entities;

/// <summary>
/// Persistent audit record for each admin-triggered backup restoration test
/// (US_089 task_003, AC-3, AC-4, DR-026).
///
/// One row per restoration test attempt, recording all validation outcomes so the
/// quarterly compliance schedule can be tracked and reported via the admin API.
/// </summary>
public sealed class RestorationTestLog
{
    /// <summary>Primary key — generated by the application (<c>Guid.NewGuid()</c>).</summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>Name of the backup file that was decrypted and restored.</summary>
    public string BackupFileName { get; set; } = string.Empty;

    /// <summary>True only when all three validation checks pass.</summary>
    public bool OverallSuccess { get; set; }

    /// <summary>Row count validation result (AC-4).</summary>
    public bool RowCountsPassed { get; set; }

    /// <summary>Referential integrity (FK constraint) validation result (AC-4).</summary>
    public bool ReferentialIntegrityPassed { get; set; }

    /// <summary>Table-level checksum validation result (AC-4).</summary>
    public bool ChecksumsPassed { get; set; }

    /// <summary>Elapsed time for the <c>pg_restore</c> operation.</summary>
    public TimeSpan RestorationDuration { get; set; }

    /// <summary>
    /// JSON-serialized error or validation failure details (null on full success).
    /// Max 4000 characters.
    /// </summary>
    public string? ErrorDetails { get; set; }

    /// <summary>
    /// Identity of the admin user who triggered the test (sub claim / username).
    /// Max 256 characters.
    /// </summary>
    public string PerformedBy { get; set; } = string.Empty;

    /// <summary>UTC timestamp when this restoration test was executed.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}
