// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPACIP.DataAccess;

#nullable disable

namespace UPACIP.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422052804_AddPatientContactUpdateFields")]
    partial class AddPatientContactUpdateFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6"),
                            ConcurrencyStamp = "a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6",
                            Description = "End-user patient portal access — read-only appointment and record visibility.",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-f2a3b4c5d6e7"),
                            ConcurrencyStamp = "b2c3d4e5-f6a7-8b9c-0d1e-f2a3b4c5d6e7",
                            Description = "Clinical staff — schedule management, appointment actions, and patient record access.",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-9c0d-1e2f-a3b4c5d6e7f8"),
                            ConcurrencyStamp = "c3d4e5f6-a7b8-9c0d-1e2f-a3b4c5d6e7f8",
                            Description = "Platform administrator — full system access including user management and configuration.",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PendingVerification");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MfaEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MfaRecoveryCodes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TotpSecretEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppointmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BookingReference")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsRiskEstimated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWalkIn")
                        .HasColumnType("boolean");

                    b.Property<string>("NoShowRiskBand")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("NoShowRiskScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("RequiresOutreach")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RiskCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentTime")
                        .HasDatabaseName("ix_appointments_appointment_time");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.HasIndex("AppointmentTime", "Status")
                        .HasDatabaseName("ix_appointments_appointment_time_status");

                    b.HasIndex("NoShowRiskScore", "Status")
                        .HasDatabaseName("ix_appointments_no_show_risk_score_status");

                    b.HasIndex("PatientId", "AppointmentTime")
                        .IsUnique()
                        .HasDatabaseName("ix_appointments_patient_id_appointment_time");

                    b.HasIndex("AppointmentTime", "Status", "ProviderId")
                        .HasDatabaseName("ix_appointments_appointment_time_status_provider_id");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.HasIndex("Action", "Timestamp")
                        .HasDatabaseName("ix_audit_logs_action_timestamp");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("ix_audit_logs_user_id_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ClinicalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentCategory")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploaderUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_clinical_documents_patient_id");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("ix_clinical_documents_processing_status");

                    b.HasIndex("UploaderUserId");

                    b.ToTable("clinical_documents", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_email_verification_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_verification_tokens_user_id");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ExtractedData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FlaggedForReview")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceAttribution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_extracted_data_document_id");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("extracted_data", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.InsuranceValidationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PolicyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("policy_prefix");

                    b.Property<string>("ProviderKeyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_keyword");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKeyword")
                        .HasDatabaseName("ix_insurance_validation_records_provider_keyword");

                    b.ToTable("insurance_validation_records", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.IntakeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AiSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_session_id");

                    b.Property<string>("AiSessionStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ai_session_status");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InsuranceRequiresStaffFollowup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("insurance_requires_staff_followup");

                    b.Property<string>("InsuranceReviewReason")
                        .HasColumnType("text")
                        .HasColumnName("insurance_review_reason");

                    b.Property<DateTime?>("InsuranceValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("insurance_validated_at");

                    b.Property<string>("InsuranceValidationStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("insurance_validation_status");

                    b.Property<string>("IntakeMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("LastAutoSavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_auto_saved_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AiSessionId")
                        .HasDatabaseName("ix_intake_data_ai_session_id")
                        .HasFilter("ai_session_id IS NOT NULL");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_intake_data_patient_id");

                    b.HasIndex("PatientId", "AiSessionStatus")
                        .HasDatabaseName("ix_intake_data_patient_ai_status")
                        .HasFilter("ai_session_status IS NOT NULL");

                    b.HasIndex("PatientId", "InsuranceRequiresStaffFollowup")
                        .HasDatabaseName("ix_intake_data_insurance_staff_followup")
                        .HasFilter("insurance_requires_staff_followup = true AND completed_at IS NOT NULL");

                    b.ToTable("intake_data", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.MedicalCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("AiConfidenceScore")
                        .HasColumnType("real");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SuggestedByAi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("PatientId", "CodeType", "CodeValue")
                        .HasDatabaseName("ix_medical_codes_patient_codetype_codevalue");

                    b.ToTable("medical_codes", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.NotificationLog", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryChannel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("NotificationId");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("ix_notification_logs_appointment_id");

                    b.ToTable("notification_logs", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_password_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AutoSwapDisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AutoSwapDisabledByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutoSwapDisabledReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AutoSwapEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ContactUpdateRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ContactUpdateRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_email");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ProviderAvailabilityTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("General Checkup");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SlotDurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_provider_availability_templates_provider_id");

                    b.HasIndex("ProviderId", "DayOfWeek")
                        .HasDatabaseName("ix_provider_availability_templates_provider_id_day_of_week");

                    b.HasIndex("ProviderId", "DayOfWeek", "StartTime")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_availability_templates_provider_day_start");

                    b.ToTable("provider_availability_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_provider_availability_templates_end_after_start", "end_time > start_time");

                            t.HasCheckConstraint("ck_provider_availability_templates_slot_duration_positive", "slot_duration_minutes > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1e2ecb5-b5c6-7890-abcd-ef1234567892"),
                            AppointmentType = "General Checkup",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("d1e2f3a4-b5c6-7890-abcd-ef1234567890"),
                            ProviderName = "Dr. Emily Chen",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1e2ec86-b5c6-7890-abcd-ef1234567893"),
                            AppointmentType = "General Checkup",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("d1e2f3a4-b5c6-7890-abcd-ef1234567890"),
                            ProviderName = "Dr. Emily Chen",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1e2ec97-b5c6-7890-abcd-ef1234567894"),
                            AppointmentType = "General Checkup",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("d1e2f3a4-b5c6-7890-abcd-ef1234567890"),
                            ProviderName = "Dr. Emily Chen",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1e2ece0-b5c6-7890-abcd-ef1234567895"),
                            AppointmentType = "General Checkup",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("d1e2f3a4-b5c6-7890-abcd-ef1234567890"),
                            ProviderName = "Dr. Emily Chen",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d1e2ecf1-b5c6-7890-abcd-ef1234567896"),
                            AppointmentType = "General Checkup",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("d1e2f3a4-b5c6-7890-abcd-ef1234567890"),
                            ProviderName = "Dr. Emily Chen",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(8, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2f39aa4-c6d7-8901-bcde-f12345678902"),
                            AppointmentType = "Consultation",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("e2f3a4b5-c6d7-8901-bcde-f12345678901"),
                            ProviderName = "Dr. Michael Park",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2f39a97-c6d7-8901-bcde-f12345678905"),
                            AppointmentType = "Consultation",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 2,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("e2f3a4b5-c6d7-8901-bcde-f12345678901"),
                            ProviderName = "Dr. Michael Park",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2f39a86-c6d7-8901-bcde-f12345678904"),
                            AppointmentType = "Consultation",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("e2f3a4b5-c6d7-8901-bcde-f12345678901"),
                            ProviderName = "Dr. Michael Park",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2f39af1-c6d7-8901-bcde-f12345678907"),
                            AppointmentType = "Consultation",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 4,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("e2f3a4b5-c6d7-8901-bcde-f12345678901"),
                            ProviderName = "Dr. Michael Park",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e2f39ae0-c6d7-8901-bcde-f12345678906"),
                            AppointmentType = "Consultation",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(16, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("e2f3a4b5-c6d7-8901-bcde-f12345678901"),
                            ProviderName = "Dr. Michael Park",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(9, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3a4e8d7-d7e8-9012-cdef-123456789016"),
                            AppointmentType = "Follow-up",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            EndTime = new TimeOnly(15, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("f3a4b5c6-d7e8-9012-cdef-123456789012"),
                            ProviderName = "Dr. Lisa Wang",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(10, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3a4e8f5-d7e8-9012-cdef-123456789014"),
                            AppointmentType = "Follow-up",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            EndTime = new TimeOnly(15, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("f3a4b5c6-d7e8-9012-cdef-123456789012"),
                            ProviderName = "Dr. Lisa Wang",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(10, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3a4e893-d7e8-9012-cdef-12345678901a"),
                            AppointmentType = "Follow-up",
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 5,
                            EndTime = new TimeOnly(15, 0, 0),
                            IsActive = true,
                            ProviderId = new Guid("f3a4b5c6-d7e8-9012-cdef-123456789012"),
                            ProviderName = "Dr. Lisa Wang",
                            SlotDurationMinutes = 30,
                            StartTime = new TimeOnly(10, 0, 0),
                            UpdatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ArrivalTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WaitTimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_queue_entries_appointment_id");

                    b.ToTable("queue_entries", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.UserSession", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpirationReason")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LogoutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LogId");

                    b.HasIndex("LoginAt")
                        .HasDatabaseName("ix_user_sessions_login_at");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_user_sessions_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.WaitlistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ClaimExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastNotifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OfferedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferedSlotId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PreferredDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("PreferredEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("PreferredProviderId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("PreferredStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClaimToken")
                        .IsUnique()
                        .HasDatabaseName("ix_waitlist_entries_claim_token")
                        .HasFilter("claim_token IS NOT NULL");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_waitlist_entries_patient_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_waitlist_entries_status");

                    b.HasIndex("PreferredDate", "PreferredProviderId")
                        .HasDatabaseName("ix_waitlist_entries_preferred_date_provider");

                    b.ToTable("waitlist_entries", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.Appointment", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.PreferredSlotCriteria", "PreferredSlotCriteria", b1 =>
                        {
                            b1.Property<Guid>("AppointmentId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("MaxWaitMinutes")
                                .HasColumnType("integer");

                            b1.Property<string>("Notes")
                                .HasColumnType("text");

                            b1.Property<List<string>>("PreferredDays")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("PreferredTimeOfDay")
                                .HasColumnType("text");

                            b1.HasKey("AppointmentId");

                            b1.ToTable("appointments");

                            b1.ToJson("PreferredSlotCriteria");

                            b1.WithOwner()
                                .HasForeignKey("AppointmentId");
                        });

                    b.Navigation("Patient");

                    b.Navigation("PreferredSlotCriteria");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.AuditLog", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ClinicalDocument", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.Patient", "Patient")
                        .WithMany("ClinicalDocuments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "UploaderUser")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("UploaderUser");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ExtractedData", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ClinicalDocument", "Document")
                        .WithMany("ExtractedData")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.ExtractedDataContent", "DataContent", b1 =>
                        {
                            b1.Property<Guid>("ExtractedDataId")
                                .HasColumnType("uuid");

                            b1.Property<Dictionary<string, string>>("Metadata")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("NormalizedValue")
                                .HasColumnType("text");

                            b1.Property<string>("RawText")
                                .HasColumnType("text");

                            b1.Property<string>("SourceSnippet")
                                .HasColumnType("text");

                            b1.Property<string>("Unit")
                                .HasColumnType("text");

                            b1.HasKey("ExtractedDataId");

                            b1.ToTable("extracted_data");

                            b1.ToJson("DataContent");

                            b1.WithOwner()
                                .HasForeignKey("ExtractedDataId");
                        });

                    b.Navigation("DataContent");

                    b.Navigation("Document");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.IntakeData", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.Patient", "Patient")
                        .WithMany("IntakeRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.AiSessionSnapshot", "AiSessionSnapshot", b1 =>
                        {
                            b1.Property<Guid>("IntakeDataId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConsecutiveProviderFailures")
                                .HasColumnType("integer");

                            b1.Property<string>("CurrentFieldKey")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("TurnCount")
                                .HasColumnType("integer");

                            b1.HasKey("IntakeDataId");

                            b1.ToTable("intake_data");

                            b1.ToJson("ai_session_snapshot");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDataId");

                            b1.OwnsMany("UPACIP.DataAccess.Entities.OwnedTypes.AiCollectedField", "CollectedFields", b2 =>
                                {
                                    b2.Property<Guid>("AiSessionSnapshotIntakeDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Key")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("AiSessionSnapshotIntakeDataId", "Id");

                                    b2.ToTable("intake_data");

                                    b2.WithOwner()
                                        .HasForeignKey("AiSessionSnapshotIntakeDataId");
                                });

                            b1.Navigation("CollectedFields");
                        });

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.GuardianConsentSnapshot", "GuardianConsent", b1 =>
                        {
                            b1.Property<Guid>("IntakeDataId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("ConsentAcknowledged")
                                .HasColumnType("boolean");

                            b1.Property<DateTime?>("ConsentRecordedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("GuardianDateOfBirth")
                                .HasColumnType("text");

                            b1.Property<string>("GuardianName")
                                .HasColumnType("text");

                            b1.Property<string>("GuardianRelationship")
                                .HasColumnType("text");

                            b1.HasKey("IntakeDataId");

                            b1.ToTable("intake_data");

                            b1.ToJson("guardian_consent");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDataId");
                        });

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.InsuranceInfo", "InsuranceInfo", b1 =>
                        {
                            b1.Property<Guid>("IntakeDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GroupNumber")
                                .HasColumnType("text");

                            b1.Property<DateOnly?>("PolicyExpiryDate")
                                .HasColumnType("date");

                            b1.Property<string>("PolicyNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PrimaryInsuredName")
                                .HasColumnType("text");

                            b1.Property<string>("Provider")
                                .HasColumnType("text");

                            b1.HasKey("IntakeDataId");

                            b1.ToTable("intake_data");

                            b1.ToJson("InsuranceInfo");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDataId");
                        });

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.IntakeAttributionSnapshot", "AttributionSnapshot", b1 =>
                        {
                            b1.Property<Guid>("IntakeDataId")
                                .HasColumnType("uuid");

                            b1.HasKey("IntakeDataId");

                            b1.ToTable("intake_data");

                            b1.ToJson("intake_attribution");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDataId");

                            b1.OwnsMany("UPACIP.DataAccess.Entities.OwnedTypes.IntakeConflictNote", "ConflictNotes", b2 =>
                                {
                                    b2.Property<Guid>("IntakeAttributionSnapshotIntakeDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("FieldKey")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("RecordedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("ReplacedSource")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ReplacedValue")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("WinningSource")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("WinningValue")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("IntakeAttributionSnapshotIntakeDataId", "Id");

                                    b2.ToTable("intake_data");

                                    b2.WithOwner()
                                        .HasForeignKey("IntakeAttributionSnapshotIntakeDataId");
                                });

                            b1.OwnsMany("UPACIP.DataAccess.Entities.OwnedTypes.IntakeFieldAttribution", "FieldAttributions", b2 =>
                                {
                                    b2.Property<Guid>("IntakeAttributionSnapshotIntakeDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("CollectedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("FieldKey")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Source")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("IntakeAttributionSnapshotIntakeDataId", "Id");

                                    b2.ToTable("intake_data");

                                    b2.WithOwner()
                                        .HasForeignKey("IntakeAttributionSnapshotIntakeDataId");
                                });

                            b1.OwnsMany("UPACIP.DataAccess.Entities.OwnedTypes.IntakeModeSwitchEvent", "ModeSwitchEvents", b2 =>
                                {
                                    b2.Property<Guid>("IntakeAttributionSnapshotIntakeDataId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("CorrelationId")
                                        .HasColumnType("text");

                                    b2.Property<string>("FromMode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("SwitchedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("ToMode")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("IntakeAttributionSnapshotIntakeDataId", "Id");

                                    b2.ToTable("intake_data");

                                    b2.WithOwner()
                                        .HasForeignKey("IntakeAttributionSnapshotIntakeDataId");
                                });

                            b1.Navigation("ConflictNotes");

                            b1.Navigation("FieldAttributions");

                            b1.Navigation("ModeSwitchEvents");
                        });

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.IntakeMandatoryFields", "MandatoryFields", b1 =>
                        {
                            b1.Property<Guid>("IntakeDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Allergies")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ChiefComplaint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<List<string>>("CurrentMedications")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("MedicalHistory")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("IntakeDataId");

                            b1.ToTable("intake_data");

                            b1.ToJson("MandatoryFields");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDataId");
                        });

                    b.OwnsOne("UPACIP.DataAccess.Entities.OwnedTypes.IntakeOptionalFields", "OptionalFields", b1 =>
                        {
                            b1.Property<Guid>("IntakeDataId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdditionalNotes")
                                .HasColumnType("text");

                            b1.Property<string>("FamilyHistory")
                                .HasColumnType("text");

                            b1.Property<string>("ReviewOfSystems")
                                .HasColumnType("text");

                            b1.Property<string>("SocialHistory")
                                .HasColumnType("text");

                            b1.HasKey("IntakeDataId");

                            b1.ToTable("intake_data");

                            b1.ToJson("OptionalFields");

                            b1.WithOwner()
                                .HasForeignKey("IntakeDataId");
                        });

                    b.Navigation("AiSessionSnapshot");

                    b.Navigation("AttributionSnapshot");

                    b.Navigation("GuardianConsent");

                    b.Navigation("InsuranceInfo");

                    b.Navigation("MandatoryFields");

                    b.Navigation("OptionalFields");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.MedicalCode", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UPACIP.DataAccess.Entities.Patient", "Patient")
                        .WithMany("MedicalCodes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.NotificationLog", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.Appointment", "Appointment")
                        .WithMany("Notifications")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ProviderAvailabilityTemplate", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.QueueEntry", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.Appointment", "Appointment")
                        .WithOne("QueueEntry")
                        .HasForeignKey("UPACIP.DataAccess.Entities.QueueEntry", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.UserSession", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.WaitlistEntry", b =>
                {
                    b.HasOne("UPACIP.DataAccess.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UploadedDocuments");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.Appointment", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("QueueEntry");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.ClinicalDocument", b =>
                {
                    b.Navigation("ExtractedData");
                });

            modelBuilder.Entity("UPACIP.DataAccess.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ClinicalDocuments");

                    b.Navigation("IntakeRecords");

                    b.Navigation("MedicalCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
