using System.ComponentModel.DataAnnotations;

namespace UPACIP.Api.Models;

// ─────────────────────────────────────────────────────────────────────────────
// Request DTOs
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Request body for <c>POST /api/coding/icd10/generate</c> (US_047, AC-1, AC-4).
///
/// References the extracted diagnosis IDs produced by the clinical data extraction
/// pipeline (US_040, cross-epic EP-006 dependency).
/// </summary>
public sealed record Icd10MappingRequestDto
{
    /// <summary>
    /// Primary key of the patient whose diagnoses should be coded.
    /// Must match the authenticated user's patient record or the caller must hold the Staff/Admin role.
    /// </summary>
    [Required]
    public Guid PatientId { get; init; }

    /// <summary>
    /// Non-empty list of <c>ExtractedData</c> primary keys representing the diagnosis entries
    /// to be mapped to ICD-10 codes.  CPT-class extractions are ignored by the coding service.
    ///
    /// Maximum 50 IDs per request to bound token budget (AIR-O07).
    /// </summary>
    [Required]
    [MinLength(1, ErrorMessage = "At least one diagnosis ID is required.")]
    [MaxLength(50, ErrorMessage = "Maximum 50 diagnosis IDs per request.")]
    public IReadOnlyList<Guid> DiagnosisIds { get; init; } = [];

    /// <summary>
    /// Optional client-supplied idempotency key (NFR-034).
    /// When provided, duplicate requests carrying the same key within a 24-hour window
    /// receive the original job ID instead of enqueuing a second job.
    /// Max 64 characters; recommended value: UUID v4 generated by the caller.
    /// </summary>
    [MaxLength(64)]
    public string? IdempotencyKey { get; init; }
}

/// <summary>
/// Request body for <c>POST /api/coding/icd10/library/refresh</c> (US_047, AC-3, Admin-only).
///
/// Carries the new quarterly ICD-10 library dataset.  For large datasets (1 000+ codes)
/// this endpoint accepts a chunked upload and returns a summary; the actual upsert is
/// performed transactionally so that partial failures roll back completely.
/// </summary>
public sealed record LibraryRefreshRequestDto
{
    /// <summary>
    /// Semantic version identifier for this library release (e.g. <c>"2026.2"</c>).
    /// Must be strictly greater than the latest version already in the database.
    /// Max 20 characters.
    /// </summary>
    [Required]
    [MaxLength(20)]
    public string Version { get; init; } = string.Empty;

    /// <summary>
    /// The complete set of ICD-10 codes belonging to this library version.
    /// All codes not present in this list will have <c>is_current</c> set to <c>false</c>
    /// and <c>deprecated_date</c> stamped with today's date.
    ///
    /// Must not be empty — an empty list would mark all existing codes as deprecated.
    /// </summary>
    [Required]
    [MinLength(1, ErrorMessage = "At least one code entry is required.")]
    public IReadOnlyList<Icd10LibraryCodeEntryDto> Codes { get; init; } = [];
}

/// <summary>
/// A single ICD-10 code entry within a <see cref="LibraryRefreshRequestDto"/>.
/// </summary>
public sealed record Icd10LibraryCodeEntryDto
{
    /// <summary>ICD-10 alphanumeric code value (e.g. <c>"J18.9"</c>). Max 10 chars.</summary>
    [Required]
    [MaxLength(10)]
    public string CodeValue { get; init; } = string.Empty;

    /// <summary>Full clinical description. Max 500 chars.</summary>
    [Required]
    [MaxLength(500)]
    public string Description { get; init; } = string.Empty;

    /// <summary>ICD-10 chapter or block category label. Max 100 chars.</summary>
    [Required]
    [MaxLength(100)]
    public string Category { get; init; } = string.Empty;

    /// <summary>Date from which this code became effective in the ICD-10 standard.</summary>
    [Required]
    public DateOnly EffectiveDate { get; init; }

    /// <summary>Optional deprecation date; <c>null</c> for active codes.</summary>
    public DateOnly? DeprecatedDate { get; init; }

    /// <summary>Optional successor code when this code is being deprecated. Max 10 chars.</summary>
    [MaxLength(10)]
    public string? ReplacementCode { get; init; }
}

// ─────────────────────────────────────────────────────────────────────────────
// Response DTOs
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Response returned by <c>POST /api/coding/icd10/generate</c> (202 Accepted, NFR-029).
///
/// The mapping job is processed asynchronously; callers poll
/// <c>GET /api/coding/icd10/pending?patientId={id}</c> for results.
/// </summary>
public sealed record Icd10MappingAcceptedDto
{
    /// <summary>Unique identifier for the enqueued coding job.</summary>
    public Guid JobId { get; init; }

    /// <summary>Echoes back the patient ID for client-side correlation.</summary>
    public Guid PatientId { get; init; }

    /// <summary>UTC timestamp when the job was accepted and enqueued.</summary>
    public DateTime AcceptedAt { get; init; }

    /// <summary>
    /// Human-readable status message explaining that the job has been queued and
    /// results will be available via the pending endpoint.
    /// </summary>
    public string Message { get; init; } = string.Empty;
}

/// <summary>
/// Individual ICD-10 code suggestion returned in a <see cref="Icd10MappingResponseDto"/>
/// (US_047, AC-1, AC-4).
/// </summary>
public sealed record Icd10CodeDto
{
    /// <summary>MedicalCode primary key in the database (null for uncodable entries not yet persisted).</summary>
    public Guid? MedicalCodeId { get; init; }

    /// <summary>
    /// ICD-10 code value (e.g. <c>"J18.9"</c>).
    /// Set to <c>"UNCODABLE"</c> when no match was found (edge case, AC-1).
    /// </summary>
    public string CodeValue { get; init; } = string.Empty;

    /// <summary>Clinical description of the code.</summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>AI model confidence in the range [0.0, 1.0]. <c>0.00</c> for uncodable entries.</summary>
    public float ConfidenceScore { get; init; }

    /// <summary>
    /// AI-generated justification explaining why this code was mapped to the diagnosis (AC-1).
    /// Fixed message for uncodable entries.
    /// </summary>
    public string Justification { get; init; } = string.Empty;

    /// <summary>
    /// Rank among sibling codes for the same diagnosis (1 = highest relevance, AC-4).
    /// <c>null</c> when only a single code applies or the entry is uncodable.
    /// </summary>
    public int? RelevanceRank { get; init; }

    /// <summary>
    /// Current revalidation lifecycle state.
    /// <c>null</c> until the first quarterly library refresh pass.
    /// </summary>
    public string? ValidationStatus { get; init; }

    /// <summary>ICD-10 library version against which this code was validated.</summary>
    public string? LibraryVersion { get; init; }

    /// <summary><c>true</c> when this entry requires staff review before use.</summary>
    public bool RequiresReview { get; init; }
}

/// <summary>
/// Response returned by <c>GET /api/coding/icd10/pending?patientId={id}</c> (US_047, AC-1, AC-4).
///
/// Contains both successfully mapped codes and diagnoses that could not be coded.
/// Codes are sorted by <c>relevance_rank</c> ascending (highest relevance first).
/// </summary>
public sealed record Icd10MappingResponseDto
{
    /// <summary>Patient this result set belongs to.</summary>
    public Guid PatientId { get; init; }

    /// <summary>All ICD-10 codes suggested or confirmed for this patient, ranked by relevance.</summary>
    public IReadOnlyList<Icd10CodeDto> Codes { get; init; } = [];

    /// <summary>
    /// IDs of extracted diagnoses for which no matching ICD-10 code was found.
    /// These entries have a corresponding <c>"UNCODABLE"</c> entry in <see cref="Codes"/>
    /// and are flagged for manual coding (edge case).
    /// </summary>
    public IReadOnlyList<Guid> UnmappedDiagnosisIds { get; init; } = [];

    /// <summary>UTC timestamp of the most recent coding run for this patient.</summary>
    public DateTime? LastCodingRunAt { get; init; }
}

/// <summary>
/// Summary result returned by <c>POST /api/coding/icd10/library/refresh</c> (US_047, AC-3).
/// </summary>
public sealed record LibraryRefreshResultDto
{
    /// <summary>Library version that was just applied.</summary>
    public string Version { get; init; } = string.Empty;

    /// <summary>Number of new ICD-10 code entries inserted.</summary>
    public int CodesAdded { get; init; }

    /// <summary>Number of existing entries marked as deprecated in this refresh.</summary>
    public int CodesDeprecated { get; init; }

    /// <summary>
    /// Number of pending <c>MedicalCode</c> records revalidated as part of this refresh (AC-3).
    /// </summary>
    public int PendingCodesRevalidated { get; init; }

    /// <summary>
    /// Number of <c>MedicalCode</c> records that reference a newly deprecated code and
    /// have been flagged <c>DeprecatedReplaced</c> for staff review (edge case).
    /// </summary>
    public int DeprecatedRecordsFlagged { get; init; }

    /// <summary>UTC timestamp when the refresh completed.</summary>
    public DateTime RefreshedAt { get; init; }
}

/// <summary>
/// Summary result returned by <c>POST /api/coding/icd10/library/revalidate</c> (US_047, AC-3).
/// </summary>
public sealed record RevalidationResultDto
{
    /// <summary>Total number of pending <c>MedicalCode</c> records examined.</summary>
    public int TotalExamined { get; init; }

    /// <summary>Number of records confirmed as still valid against the current library.</summary>
    public int MarkedValid { get; init; }

    /// <summary>Number of records flagged as <c>DeprecatedReplaced</c> (edge case).</summary>
    public int MarkedDeprecated { get; init; }

    /// <summary>Number of records set to <c>PendingReview</c> due to ambiguous match.</summary>
    public int MarkedPendingReview { get; init; }

    /// <summary>UTC timestamp when the revalidation run completed.</summary>
    public DateTime RevalidatedAt { get; init; }
}
