using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace UPACIP.Api.Models;

// ─────────────────────────────────────────────────────────────────────────────
// Request DTOs
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// Request body for <c>PUT /api/codes/{codeId}/override</c> (US_049, AC-3).
/// Staff must supply a replacement code value, description, and a justification of
/// at least 10 characters (HIPAA audit requirement).
/// </summary>
public sealed record OverrideCodeRequestDto
{
    /// <summary>
    /// Replacement CPT or ICD-10 code value selected from the code-search interface.
    /// Max 20 characters.
    /// </summary>
    [Required(ErrorMessage = "new_code_value is required.")]
    [MaxLength(20, ErrorMessage = "new_code_value must not exceed 20 characters.")]
    [JsonPropertyName("new_code_value")]
    public string NewCodeValue { get; init; } = string.Empty;

    /// <summary>
    /// Clinical description that corresponds to <see cref="NewCodeValue"/>.
    /// Max 500 characters.
    /// </summary>
    [Required(ErrorMessage = "new_description is required.")]
    [MaxLength(500, ErrorMessage = "new_description must not exceed 500 characters.")]
    [JsonPropertyName("new_description")]
    public string NewDescription { get; init; } = string.Empty;

    /// <summary>
    /// Mandatory clinical justification explaining why the AI suggestion was incorrect.
    /// Minimum 10 characters (HIPAA §164.312(b), AC-3).
    /// Max 1 000 characters.
    /// </summary>
    [Required(ErrorMessage = "justification is required.")]
    [MinLength(10, ErrorMessage = "justification must be at least 10 characters.")]
    [MaxLength(1000, ErrorMessage = "justification must not exceed 1 000 characters.")]
    [JsonPropertyName("justification")]
    public string Justification { get; init; } = string.Empty;
}

// ─────────────────────────────────────────────────────────────────────────────
// Response DTOs
// ─────────────────────────────────────────────────────────────────────────────

/// <summary>
/// A single item in the staff verification queue (US_049, AC-1).
/// Maps to the SCR-014 Medical Coding Review list row.
/// </summary>
public sealed record VerificationQueueDto
{
    /// <summary>Primary key of the <c>MedicalCode</c> row.</summary>
    [JsonPropertyName("code_id")]
    public Guid CodeId { get; init; }

    /// <summary>Coding standard in lowercase (<c>"icd10"</c> or <c>"cpt"</c>).</summary>
    [JsonPropertyName("code_type")]
    public string CodeType { get; init; } = string.Empty;

    /// <summary>AI-suggested code value (e.g. <c>"J18.9"</c> or <c>"99213"</c>).</summary>
    [JsonPropertyName("code_value")]
    public string CodeValue { get; init; } = string.Empty;

    /// <summary>Human-readable description of the code.</summary>
    [JsonPropertyName("description")]
    public string Description { get; init; } = string.Empty;

    /// <summary>AI-generated clinical justification for this code suggestion.</summary>
    [JsonPropertyName("justification")]
    public string Justification { get; init; } = string.Empty;

    /// <summary>
    /// AI confidence score in [0.0, 1.0]; <c>null</c> for manually entered codes.
    /// Scores below 0.80 indicate lower AI confidence and may warrant closer review.
    /// </summary>
    [JsonPropertyName("ai_confidence_score")]
    public float? AiConfidenceScore { get; init; }

    /// <summary>Current review lifecycle state of this code record.</summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = string.Empty;

    /// <summary><c>true</c> when the code was generated by the AI pipeline.</summary>
    [JsonPropertyName("suggested_by_ai")]
    public bool SuggestedByAi { get; init; }

    /// <summary>
    /// <c>true</c> when the code library has marked this code as deprecated.
    /// The UI should block the "Approve" button and display a deprecation notice (EC-1).
    /// </summary>
    [JsonPropertyName("is_deprecated")]
    public bool IsDeprecated { get; init; }

    /// <summary>UTC timestamp when the AI-generated code was first persisted.</summary>
    [JsonPropertyName("created_at")]
    public DateTime CreatedAt { get; init; }
}

/// <summary>
/// Response body for a successful code approval (US_049, AC-2).
/// </summary>
public sealed record ApproveCodeResponseDto
{
    /// <summary>Primary key of the approved <c>MedicalCode</c> row.</summary>
    [JsonPropertyName("code_id")]
    public Guid CodeId { get; init; }

    /// <summary>Always <c>"verified"</c> for a successful approval.</summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = "verified";

    /// <summary>UTC timestamp when the approval was recorded.</summary>
    [JsonPropertyName("verified_at")]
    public DateTime? VerifiedAt { get; init; }
}

/// <summary>
/// Response body for a successful code override (US_049, AC-3, AC-4).
/// </summary>
public sealed record OverrideCodeResponseDto
{
    /// <summary>Primary key of the overridden <c>MedicalCode</c> row.</summary>
    [JsonPropertyName("code_id")]
    public Guid CodeId { get; init; }

    /// <summary>Always <c>"overridden"</c> for a successful override.</summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = "overridden";

    /// <summary>The original AI-suggested code value captured at the time of override.</summary>
    [JsonPropertyName("original_code_value")]
    public string? OriginalCodeValue { get; init; }

    /// <summary>The replacement code value supplied by the staff member.</summary>
    [JsonPropertyName("new_code_value")]
    public string NewCodeValue { get; init; } = string.Empty;

    /// <summary>The justification recorded in the audit log.</summary>
    [JsonPropertyName("justification")]
    public string Justification { get; init; } = string.Empty;
}

/// <summary>
/// One search result from the code-library search interface shown in the override modal (US_049, AC-3).
/// </summary>
public sealed record CodeSearchResultDto
{
    /// <summary>Code value (e.g. <c>"J18.9"</c> or <c>"99213"</c>).</summary>
    [JsonPropertyName("code_value")]
    public string CodeValue { get; init; } = string.Empty;

    /// <summary>Clinical description.</summary>
    [JsonPropertyName("description")]
    public string Description { get; init; } = string.Empty;

    /// <summary>Category label from the code library.</summary>
    [JsonPropertyName("category")]
    public string Category { get; init; } = string.Empty;
}

/// <summary>
/// A single immutable entry from the <c>coding_audit_log</c> table (US_049, AC-4).
/// </summary>
public sealed record CodingAuditEntryDto
{
    /// <summary>Primary key of the audit log row.</summary>
    [JsonPropertyName("log_id")]
    public Guid LogId { get; init; }

    /// <summary>Action label (e.g. <c>"Approved"</c>, <c>"Overridden"</c>, <c>"DeprecatedBlocked"</c>).</summary>
    [JsonPropertyName("action")]
    public string Action { get; init; } = string.Empty;

    /// <summary>Code value before this action.</summary>
    [JsonPropertyName("old_code_value")]
    public string OldCodeValue { get; init; } = string.Empty;

    /// <summary>Code value after this action.</summary>
    [JsonPropertyName("new_code_value")]
    public string NewCodeValue { get; init; } = string.Empty;

    /// <summary>Override justification text; <c>null</c> for non-override events.</summary>
    [JsonPropertyName("justification")]
    public string? Justification { get; init; }

    /// <summary>ID of the staff member who performed the action.</summary>
    [JsonPropertyName("user_id")]
    public Guid? UserId { get; init; }

    /// <summary>UTC timestamp of the action.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; init; }
}

/// <summary>
/// Verification progress summary for a patient (US_049, EC-2).
/// Drives the progress indicator on the SCR-014 screen (e.g., "3/5 codes verified").
/// </summary>
public sealed record VerificationProgressDto
{
    /// <summary>Total number of <c>MedicalCode</c> records for the patient.</summary>
    [JsonPropertyName("total_codes")]
    public int TotalCodes { get; init; }

    /// <summary>Number of codes with status <c>Verified</c>.</summary>
    [JsonPropertyName("verified_count")]
    public int VerifiedCount { get; init; }

    /// <summary>Number of codes with status <c>Overridden</c>.</summary>
    [JsonPropertyName("overridden_count")]
    public int OverriddenCount { get; init; }

    /// <summary>Number of codes with status <c>Pending</c>.</summary>
    [JsonPropertyName("pending_count")]
    public int PendingCount { get; init; }

    /// <summary>Number of codes with status <c>Deprecated</c>.</summary>
    [JsonPropertyName("deprecated_count")]
    public int DeprecatedCount { get; init; }

    /// <summary>
    /// Derived human-readable label: <c>"fully verified"</c>, <c>"partially verified"</c>,
    /// or <c>"pending review"</c> (EC-2).
    /// </summary>
    [JsonPropertyName("status_label")]
    public string StatusLabel { get; init; } = string.Empty;
}

/// <summary>
/// Result of a deprecation check for a code value (US_049, EC-1).
/// When <see cref="IsDeprecated"/> is <c>true</c> the UI must display the deprecated
/// notice and block the "Approve" action.
/// </summary>
public sealed record DeprecationCheckDto
{
    /// <summary><c>true</c> when the code is no longer active in the current library.</summary>
    [JsonPropertyName("is_deprecated")]
    public bool IsDeprecated { get; init; }

    /// <summary>Human-readable deprecation notice to show the user; empty when not deprecated.</summary>
    [JsonPropertyName("deprecated_notice")]
    public string DeprecatedNotice { get; init; } = string.Empty;

    /// <summary>
    /// Suggested replacement code values from the library; may be empty when no direct
    /// replacement exists (e.g., CPT library does not carry replacement references).
    /// </summary>
    [JsonPropertyName("replacement_codes")]
    public IReadOnlyList<string> ReplacementCodes { get; init; } = [];
}

/// <summary>
/// Response body for a 409 Conflict when staff attempts to approve a deprecated code (US_049, EC-1).
/// Carries the same payload as <see cref="DeprecationCheckDto"/> plus the standard error fields.
/// </summary>
public sealed record DeprecatedCodeConflictDto
{
    /// <summary>Always <c>"deprecated_code"</c> to allow clients to distinguish from other 409 cases.</summary>
    [JsonPropertyName("error_code")]
    public string ErrorCode { get; init; } = "deprecated_code";

    [JsonPropertyName("message")]
    public string Message { get; init; } = string.Empty;

    [JsonPropertyName("deprecated_notice")]
    public string DeprecatedNotice { get; init; } = string.Empty;

    [JsonPropertyName("replacement_codes")]
    public IReadOnlyList<string> ReplacementCodes { get; init; } = [];

    [JsonPropertyName("correlation_id")]
    public string CorrelationId { get; init; } = string.Empty;
}
