namespace UPACIP.Service.Admin;

/// <summary>
/// Business logic for admin-configurable appointment slot templates (US_059 AC-1, AC-2).
///
/// Slot templates define per-provider, per-day-of-week time blocks with appointment types
/// and availability flags.  Changes apply only to future appointments — existing bookings
/// are never modified by a template update.
///
/// Implementations must:
///   - Cache reads in Redis under <c>config:slots:{providerId}:{dayOfWeek}</c> (5-min TTL).
///   - Invalidate the relevant cache keys on every write.
///   - Handle optimistic concurrency via the entity's <c>Version</c> token.
///   - Append an AuditLog entry for every write (NFR-012, NFR-035).
/// </summary>
public interface ISlotTemplateService
{
    /// <summary>
    /// Returns the slot template for the given provider and day of the week, or
    /// <c>null</c> if no template has been configured for that combination.
    /// Reads from Redis cache (5-min TTL) with DB fallback.
    /// </summary>
    Task<SlotTemplateResponse?> GetByProviderAndDayAsync(
        Guid              providerId,
        int               dayOfWeek,
        CancellationToken ct = default);

    /// <summary>
    /// Returns all configured slot templates for the given provider (all days).
    /// Reads from Redis cache with DB fallback.
    /// </summary>
    Task<IReadOnlyList<SlotTemplateResponse>> GetByProviderAsync(
        Guid              providerId,
        CancellationToken ct = default);

    /// <summary>
    /// Returns the non-cancelled appointments that fall on any slot generated by
    /// the provider's template for <paramref name="dayOfWeek"/>, enabling the admin
    /// to preview the impact of a template change before saving.
    /// </summary>
    Task<AffectedAppointmentsResponse> GetAffectedAppointmentsAsync(
        Guid              providerId,
        int               dayOfWeek,
        CancellationToken ct = default);

    /// <summary>
    /// Creates or replaces the slot template for the given provider/day combination.
    ///
    /// <para>
    /// If a template already exists, the client must supply the current <c>Version</c>
    /// in <see cref="UpsertSlotTemplateRequest.Version"/> to prevent lost-write anomalies.
    /// A stale version returns <see cref="SlotTemplateUpsertStatus.ConcurrencyConflict"/>.
    /// </para>
    ///
    /// <para>
    /// The method validates that the referenced provider exists, replaces all existing
    /// time blocks, increments <c>Version</c>, and invalidates the cache.
    /// </para>
    /// </summary>
    Task<SlotTemplateUpsertResult> UpsertAsync(
        Guid                      providerId,
        int                       dayOfWeek,
        UpsertSlotTemplateRequest request,
        Guid                      adminUserId,
        CancellationToken         ct = default);
}
