namespace UPACIP.Api.Features.AIGateway.Contracts;

/// <summary>
/// Unified request contract for all AI operations entering the AI Gateway
/// (AC-1, AC-3, AIR-O01, AIR-O02, AIR-O03).
///
/// Consumers construct an <see cref="AIRequest"/> and hand it to
/// <see cref="UPACIP.Api.Features.AIGateway.Services.IAIGatewayService"/>;
/// the gateway handles provider selection, token-budget enforcement, and resilience.
/// </summary>
public sealed class AIRequest
{
    /// <summary>Unique identifier generated by the caller; propagated through logs.</summary>
    public Guid RequestId { get; init; } = Guid.NewGuid();

    /// <summary>Classifies the operation; drives token budget and provider routing.</summary>
    public AIRequestType RequestType { get; init; }

    /// <summary>
    /// The primary user / system prompt text submitted to the LLM.
    /// Must not be empty. PII is stripped upstream by the sanitization middleware.
    /// </summary>
    public string Prompt { get; init; } = string.Empty;

    /// <summary>Optional system-level instruction that frames the model's behaviour.</summary>
    public string? SystemMessage { get; init; }

    /// <summary>
    /// Override for the maximum number of input tokens.
    /// When &gt; 0 it further constrains the canonical budget defined by
    /// <see cref="TokenBudget.For(AIRequestType)"/>; it cannot exceed it.
    /// </summary>
    public int MaxInputTokens { get; init; }

    /// <summary>
    /// Override for the maximum number of output tokens.
    /// Same rules as <see cref="MaxInputTokens"/>.
    /// </summary>
    public int MaxOutputTokens { get; init; }

    /// <summary>
    /// Sampling temperature in the range [0.0, 2.0].
    /// 0 = deterministic; defaults to 0.2 for clinical workloads.
    /// </summary>
    public float Temperature { get; init; } = 0.2f;

    /// <summary>
    /// Arbitrary key/value bag for provider-specific extensions or
    /// downstream context (e.g., document ID, patient ID for audit trails).
    /// Values are logged by key name only — values are NOT logged to avoid PII leakage.
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();

    /// <summary>
    /// Correlation ID from the originating HTTP request (TR-028).
    /// Injected by the gateway from the <c>X-Correlation-ID</c> header.
    /// </summary>
    public string CorrelationId { get; init; } = string.Empty;
}
